### ISSUE TITLE
ioBroker - ls: cannot access '/dev/disk/by-id/': No such file or directory

### ISSUE THREAD

**Issue by schoenni** [buanet/ioBroker.docker#166]
Hi there,

i tried to install the container with `docker run -p 8081:8081 --name iobroker -v iobrokerdata:/opt/iobroker buanet/iobroker:latest`

In Step 5 i get the error message: Starting ioBroker...

host.83c6319b4140 check instance "system.adapter.admin.0" for host "83c6319b4140"
host.83c6319b4140 check instance "system.adapter.discovery.0" for host "83c6319b4140"
host.83c6319b4140 check instance "system.adapter.info.0" for host "83c6319b4140"
Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"","country":"","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.20.1","arch":"arm","adapters":{"admin":{"version":"4.1.11","platform":"Javascript/Node.js"},"discovery":{"version":"2.4.1","platform":"Javascript/Node.js"},"info":{"version":"1.7.10","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"ARMv7 Processor rev 3 (v7l)","cpus":4,"mem":8257458176,"ostype":"Linux","city":""}
hash changed or no sources cached => force download of new sources
ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

What can i do about it?

thank you!

**Comment by buanet** [comment]
Hi, I'm not sure what's wrong. Your docker Command looks good. But your Log excerpt is way too less. I would need the whole log to get some more information about your Setup... 
I wonder why the Log says `ls: cannot access '/dev/disk/by-id/': No such file or directory`. Do you have Access to the web interface? ioBroker seems to be running. If yes, did you do something there? 

Regards,
André

**Comment by buanet** [comment]
As discussed [here](https://forum.iobroker.net/topic/41918/fehler-im-synology-docker-protokoll) the error message comes from ioBroker info adapter and has no impact on the functionality of ioBroker.
I created a issue for this here: https://github.com/iobroker-community-adapters/ioBroker.info/issues/230

Regards,
André

**Comment by Mierscheid** [comment]
Hi André,

I have the same problem. Docker freshly installed, used "docker pull buanet/iobroker" to load the image. The startup ends with: 

`Starting ioBroker...


host.3a751fa9db3e check instance "system.adapter.admin.0" for host "3a751fa9db3e"

host.3a751fa9db3e check instance "system.adapter.discovery.0" for host "3a751fa9db3e"

host.3a751fa9db3e check instance "system.adapter.info.0" for host "3a751fa9db3e"

Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"","country":"","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.20.1","arch":"x64","adapters":{"admin":{"version":"4.2.1","platform":"Javascript/Node.js"},"discovery":{"version":"2.5.0","platform":"Javascript/Node.js"},"info":{"version":"1.7.10","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"AMD E2-3000 APU with Radeon(TM) HD Graphics","cpus":2,"mem":9548460032,"ostype":"Linux","city":""}

hash changed or no sources cached => force download of new sources

ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden

ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden`

System: MSI MS-A88111 (AIO-Tocuh-PC), AMD E2-3000 APU, 12 GB RAM, 120 GB SSD, Win 10.0.19042.804, Docker 20.10.2, build 2291f61, buanet/iobroker f3e6776672f3.

TIA
Regards
Michael

**Comment by buanet** [comment]
Hi Michael,

and how can I help you with that? Did you read my last post? Also make sure to read the linked Issue. 

Thank you.

Regards,
André

**Comment by Mierscheid** [comment]
Oh, sorry, I had deleted my post because you wrote that the error message should have no effect. I also thought that IOBroker should start automatically in your image. I guess it doesn't. I'll have to see how that works, haven't found anything about it yet.

**Comment by buanet** [comment]
I deleted it too. :) As I remember your log said, that iobroker was started. So your problem has to be something else... Maybe any kind of networking issue. If you still have problems, take a look at the iobroker forum thread.

Regards,
André

**Comment by buanet** [comment]
Should be solved.
