### ISSUE TITLE
js-controller update fails

### ISSUE THREAD

**Issue by Mr-Markus** [buanet/ioBroker.docker#167]
Hi there,

I am trying to update the js-controller as mentioned in https://smarthome.buanet.de/2020/10/iobroker-docker-container-updates-upgrades/ 

I use latest image buanet/iobroker:v5.1.0 with portainer and it's console with bash, but reciveing following error:

```bash
bash: /usr/bin/iobroker: /usr/bin/bash: bad interpreter: No such file or directory
```

When i try to use `docker exec container_id -it` I recive this here:

```bash
exec failed: container_linux.go:349: starting container process caused "exec: \"-it\": executable file not found in $PATH": unknown
```

Do you have any idea?

**Comment by buanet** [comment]
Hi Markus,
I don't get it.
When do you get this error? Is it when you try to connect to the shell of your ioBroker container?
So you open your container details in Portainer, then hit "Console" and "Connect"?
I just tested this with a new container. No problems to open a console session:

![image](https://user-images.githubusercontent.com/16137672/109389051-f317f700-790a-11eb-8388-51c0c3a21d0d.png)
![image](https://user-images.githubusercontent.com/16137672/109389060-fb703200-790a-11eb-9423-78fd9bd930d2.png)

So where are you running your container? When I`m googling your last error message (form docker exec) the first result is this: 
https://stackoverflow.com/questions/48001082/oci-runtime-exec-failed-exec-failed-executable-file-not-found-in-path

are you running your container in docker for windows? 

Regards,
André

**Comment by buanet** [comment]
I did a quick test in docker on my windows dev host. Your docker exec seems to be wrong:
```
PS C:\Users\andre> docker exec 41e8d22ebc43 -it           
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "-it": executable file not found in $PATH: unknown
PS C:\Users\andre> docker exec -it 41e8d22ebc43 //bin/bash
root@41e8d22ebc43:/opt/iobroker# 
```

If this solves your problem, please close the issue. Thank you.

Regards,
André

**Comment by Mr-Markus** [comment]
Hi @buanet 
all my docker hosts are Linux (Raspberry Pi) :-)
I did exactly what you showed in your screenshots. Hit "Console" and "Connect" portainer.

Hm, so I know that I didn't made anything wrong and it seems to be an error on my host. Any idea?

Thanks

**Comment by rewegit** [comment]
@Mr-Markus Try
docker exec -it 41e8d22ebc43 /bin/bash

it works for me (WSL2 Powershell and Debian)
Without /bin/bash i have the same problem.

**Comment by Mr-Markus** [comment]
`docker exec -it c6663c03c157 /bin/bash`

results with:
`root@c6663c03c157:/opt/iobroker# iobroker status`
`bash: /usr/bin/iobroker: /usr/bin/bash: bad interpreter: No such file or directory`

I use docker on Raspberry Pi OS

**Comment by Mr-Markus** [comment]
Hi@buanet ,

I got a solution for my problem. Maybe you can compare it with your file.

I checked the `/opt/iobroker/iobroker`file and my first line was:
`#!/usr/bin/bash`
I changed it to
`#!/bin/bash`
and it worked

Do you know if this is the default value? I don't know why this was necessary....

**Comment by buanet** [comment]
Hi Markus,
I checked all my Installations and tested the latest image. In any case the shebang says 
`#!/bin/bash`
I wonder how this changed in your case.
Or did you use a ioBroker directory from another system and mounted it to your docker container?

Regards,
André

**Comment by Mr-Markus** [comment]
Ok, so ist like I expected.
Hm I am not sure but it could be possible that I restored my ioBroker Installation from my Pi hardware after I reused it as a docker host.

Makes sense. Something learned :)
