### ISSUE TITLE
Node-RED: settings.js always reset to default?

### ISSUE THREAD

**Issue by nicedevil007** [buanet/ioBroker.docker#168]
Heya,

I'm running Node-RED inside ioBroker with the issue that all my global/flow/context variables are gone after a reboot.

I already figured out that the `settings.js` is located inside the folder `/opt/iobroker/node-red/`. I edited the lines for `contextStorage` but after a reboot they are default again. And yes I used ioBroker with persistent volume :)

![image](https://user-images.githubusercontent.com/17103076/108909402-cae77a00-7624-11eb-80c8-4334a170d5b6.png)

How can I solve this issue?

**Comment by Apollon77** [comment]
This is no docker issue. Teh config file is generated by iobroker anew based on current config on each adapter start.

in fact the best way is to open a PR to add it to the settings template that is located in the adapter itself ... ideally with the relevant config options.

**Comment by buanet** [comment]
I agree. This is not a Docker related issue and should be handled within the adapter.
I`ll close this. 

Regards,
André
