### ISSUE TITLE
iobroker > v5.0.0 not starting on synolgy docker

### ISSUE THREAD

**Issue by snookyly** [buanet/ioBroker.docker#170]
Hi,
I am facing the issue that currently buanet/iobroker:v5.0.0 works like a charm, but buanet/iobroker:v5.1.0 or newer doesn't. When starting node is not properly running due to missing libdbl.so.2. Error message is:
`node: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory`

docker exec into the container and running apt update shows:
`Fehl:1 http://security.debian.org/debian-security buster/updates InRelease
  Could not resolve 'security.debian.org'
Fehl:2 http://deb.debian.org/debian buster InRelease
  Could not resolve 'deb.debian.org'
Fehl:3 https://deb.nodesource.com/node_12.x buster InRelease
  Could not resolve 'deb.nodesource.com'
Fehl:4 http://deb.debian.org/debian buster-updates InRelease
  Could not resolve 'deb.debian.org'
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
W: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster/InRelease Could not resolve 'deb.debian.org'
W: Fehlschlag beim Holen von http://security.debian.org/debian-security/dists/buster/updates/InRelease Could not resolve 'security.debian.org'
W: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster-updates/InRelease Could not resolve 'deb.debian.org'
W: Fehlschlag beim Holen von https://deb.nodesource.com/node_12.x/dists/buster/InRelease Could not resolve 'deb.nodesource.com'
W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.`

As said, v5.0.0 does not have of these issues above. v5.1.0 was running properly until I moved docker from volume2 back to volume1.

Here's the complete docker log:

`------------------------------------------------------------

---------------     2021-03-27 11:47:00      ---------------

------------------------------------------------------------

 

------------------------------------------------------------

-----       Welcome to your ioBroker-container!        -----

-----          Startupscript is now running.           -----

-----                Please be patient!                -----

------------------------------------------------------------

 

------------------------------------------------------------

-----              Debugging information               -----

-----                                                  -----

-----                      System                      -----

-----               arch:      x86_64                  -----

-----                                                  -----

-----                     Versions                     -----

-----               image:     v5.1.0                  -----

-----               node:      v12.21.0                -----

-----               npm:       6.14.11                 -----

-----                                                  -----

-----                       ENV                        -----

-----               SETGID:    1000                    -----

-----               SETUID:    1000                    -----

------------------------------------------------------------

 

------------------------------------------------------------

-----         Step 1 of 5: Preparing container         -----

------------------------------------------------------------

 

Registering maintenance script as command.

Done.

 

------------------------------------------------------------

-----   Step 2 of 5: Detecting ioBroker installation   -----

------------------------------------------------------------

 

Existing installation of ioBroker detected in /opt/iobroker.

 

------------------------------------------------------------

-----   Step 3 of 5: Checking ioBroker installation    -----

------------------------------------------------------------

 

(Re)Setting folder permissions (This might take a while! Please be patient!)...

Done.

 

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...

Done.

 

node: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory

/opt/scripts/iobroker_startup.sh: Zeile 197: [: !=: Einstelliger (unärer) Operator erwartet.

------------------------------------------------------------

-----      Step 4 of 5: Applying special settings      -----

------------------------------------------------------------

 

Some adapters have special requirements/ settings which can be activated by the use of environment variables.

For more information take a look at readme.md on Github!

 

------------------------------------------------------------

-----          Step 5 of 5: ioBroker startup           -----

------------------------------------------------------------

 

Starting ioBroker...

 

node: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory`

Any ideas?

**Comment by buanet** [comment]
Hi,
I cannot confirm this issue as a general issue. I just downloaded the actual v5.1.0 image and started a new container. It works like expected. I tried an apt-get update. It is running too: 
```
root@iobrokertest:/opt/iobroker# apt-get update
Holen:1 http://security.debian.org/debian-security buster/updates InRelease [65,4 kB]
Holen:2 http://deb.debian.org/debian buster InRelease [121 kB]                                               
Holen:3 https://deb.nodesource.com/node_12.x buster InRelease [4.584 B]                                               
Holen:4 http://deb.debian.org/debian buster-updates InRelease [51,9 kB]                                               
Holen:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [269 kB]
Holen:6 http://deb.debian.org/debian buster/main amd64 Packages [7.907 kB]
Holen:7 https://deb.nodesource.com/node_12.x buster/main amd64 Packages [767 B]
Holen:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [9.504 B]
Es wurden 8.430 kB in 4 s geholt (2.379 kB/s).        
Paketlisten werden gelesen... Fertig
```
As your "apt-get update" issue seems to be DNS related 
`Could not resolve 'deb.debian.org'`
you might have any kind of networking issue. So what is your network mode? Bridged? Host? MACVLAN?

As you said
>  v5.1.0 was running properly until I moved docker from volume2 back to volume1

what does this mean? What's the whole story? 

Regards,
André

**Comment by snookyly** [comment]
Hi, thank you for your reply.
I tried all networks: Bridged, Host and MACVLAN and allways the same issue.

The whole story is that I had two volumes on the nas. I moved Docker from volume2 to volume1, and moved all the container data and adjusted the mount paths from volume2 to volume1. All other containers are working like before, except iobroker. I downgraded to v5.0.0 and the container started. Changing again to v5.1.0 and the error occurs. Launching a fresh container in either of the networks Bridged, Host and MACVLAN the error occurs. I hope this helps.

Any idea why dns issues may occur, then?

**Comment by buanet** [comment]
Hi, sorry. I have really no idea.
What do you mean with a "fresh container"? What about your ioBroker directory. Did you use the same for both Versions? Or did you try to set up a really fresh ioBroker container with an **empty** ioBroker directory? 

I've never had any DNS related issue but heard about some people who had to set an DNS server inside the container.  

If you speak German you may be joining the ioBroker Discord channel. There is some kind of chat for Docker. Maybe we can help you there to identify the root issue in your case. 

Regards,
André

**Comment by buanet** [comment]
Hi, any news to this? Could you solve it? Can this issue be closed?

Regards,
André

**Comment by buanet** [comment]
No reaction for two weeks now, so I'll close this... Please reopen if needed.

Regards,
André
