### ISSUE TITLE
Please add EXPOSE 8081

### ISSUE THREAD

**Issue by mgutt** [buanet/ioBroker.docker#172]
Unraid does not add a link to the WebUI for MACVLAN networks as long the EXPOSE port isn't defined:
https://forums.unraid.net/topic/100963-1-bau-synology-unraid-iobroker/page/3/?tab=comments#comment-936743

Current output:
![2021-04-03 21_24_50](https://user-images.githubusercontent.com/10757176/113489323-dea7bb00-94c3-11eb-888e-62e0be3a985d.png)

Working example with "host" network:
![2021-04-03 21_25_45](https://user-images.githubusercontent.com/10757176/113489329-e6fff600-94c3-11eb-971d-61c2f0d0113e.png)

**Comment by buanet** [comment]
Hi,
after some discussion and test I will add the default EXPOSE to the next version of the ioBroker Docker Image. It seems not to be in conflict with the ability to change the Admin Port by ENV. 

Regards,
André

**Comment by buanet** [comment]
This enhancement is now available in Beta. Please test.

Regards, 
André

**Comment by buanet** [comment]
Solved with [Stable Release v5.2.0](https://github.com/buanet/ioBroker.docker/releases/tag/v5.2.0).
