### ISSUE TITLE
SSH access to container for command line

### ISSUE THREAD

**Issue by ordo01** [buanet/ioBroker.docker#173]
Hi, 
I have installed the latest docker image but I am struggling with SSH access to the containter to interact with iobroker command line.
Is there a specific port configured or do I need some configuration parameters to activate SSH access to the container?

**Comment by buanet** [comment]
At the very first you should use Google and find something like this: 
https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell

If you got some more questions try to ask the community at the ioBroker forum or ioBroker Discord channel. 

If you think it should work, but it doesn't >>> Feel free to pen an issue here.

Cause its a sunny Friday: no, by default there comes not ssh with the container. Use docker exec or the commandline interface in any Docker ui (e.g. portainer). You also can (but i don't recommend) add ssh to the container as in any other Debian Linux too. 

Regards,
André

**Comment by kleinmarkus** [comment]
I am trying to update js-controller via ssh to the most recent version. But ssh into the docker container does not work for me. Thanks for your support.

**Comment by buanet** [comment]
??? Did you read this: https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell ???
Don't know what else to say...

**Comment by kleinmarkus** [comment]
> ??? Did you read this: https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell ???
> Don't know what else to say...

Hmm ... This is too many options in this article, so do you know about an explicit step-by-step guide to update the json package in the container using SSH? Thanks.

**Comment by fzzybllz** [comment]
Do you have portainer installed as docker container?
-> Go to console of iobroker container and you're in.
If not, ssh to your base system and use docker exec to switch into the cli of the container...

**Comment by kleinmarkus** [comment]
> Do you have portainer installed as docker container?
> -> Go to console of iobroker container and you're in.
> If not, ssh to your base system and use docker exec to switch into the cli of the container...

Right, but each time I am stopping iob, it seems to restart itself as the iob upgrade self is not kicking off complaining iob is still running. Any ideas?

**Comment by fzzybllz** [comment]
Try to use the maintenance functionality provided by André inside the container.
Go to container cli and type 'maintenance on', confirm by typing yes, do an 'iobroker update', 'iobroker upgrade self' and finish by 'maintenance off' + confirmation for restart. Done

**Comment by buanet** [comment]
@fzzybllz 👍 this would be the preferred way

@kleinmarkus If you want somebody to help you, please provide the Steps you are doing. (Screenshots are also welcome).
Another way to get help with iobroker is the ioBroker Forum or Discord channel. There are a lot of users (including me) who give their best to support inexperienced users. 

Regards,
André

**Comment by kleinmarkus** [comment]
> @fzzybllz 👍 this would be the preferred way
> 
> @kleinmarkus If you want somebody to help you, please provide the Steps you are doing. (Screenshots are also welcome).
> Another way to get help with iobroker is the ioBroker Forum or Discord channel. There are a lot of users (including me) who give their best to support inexperienced users.
> 
> Regards,
> André

Thanks, worked for me now.
