### ISSUE TITLE
Shorten container startup time

### ISSUE THREAD

**Issue by Stefan592** [buanet/ioBroker.docker#176]
The container needs a lot of time to start at the moment. 90% of the time is needed to change the owners of the folders. 

I suggest to do this step only when reinstalling IoBroker or restoring a backup. This will significantly reduce the startup time of the container with an existing installation. The change can be implemented very easily in the "iobroker_startup.sh" script.

**Comment by buanet** [comment]
Hi,
the question is, why does it take so much time in your setup. I don't have this problems. So it might depend on your system. 
Normally the startup script will not need much time when ownership is still correct...

To do so only when reinstalling or restoring might make the container to fail when something or someone on your docker host changes the ownership of the ioBroker data.... So it will not be guaranteed that the ownership is correct when you have started your container... 

Regards,
André

**Comment by Stefan592** [comment]
I checked my setup. The slow execution was due to a wrong NFS setting.

Please close the issue.

**Comment by Mr-Markus** [comment]
@Stefan592 
Could you share your NFS Settings, please?

I try to run it with NFS Share sinde three days without success... I own a Synology NAS and created a Shared Folder like following:
```
/volume1/rpicluster	192.168.178.3/24(rw,async,no_wdelay,crossmnt,insecure,root_squash,insecure_locks,sec=sys,anonuid=1024,anongid=100)
```

and monuted it in /etc/fstab on my pi like this:

```
# nas
192.168.178.2:/volume1/rpicluster /data nfs defaults 0 0
```

**Comment by Stefan592** [comment]
@Mr-Markus 

NFS-Server:

> /media/nas *(rw,async,no_subtree_check,all_squash,anonuid=0,anongid=0)


NFS-Client:

>SERVER:/media/nas /NFS_Share nfs defaults 0 0

**Comment by viceice** [comment]
Seeing slow extraction if initial iobroker package too. Using k3s kubernetes.

```
# /etc/exports
/exports        10.158.0.0/16(rw,sync,no_root_squash,no_subtree_check)
```

also mounting with noatime, but still very slow 😕  

```
# mount options (autogenerated)
10.158.0.10:/exports/nfs/xxx  /var/lib/kubelet/pods/xxx type nfs4 (rw,noatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.158.0.11,local_lock=none,addr=10.158.0.10)
```

**Comment by viceice** [comment]
Maybe the overlay mounts ar an issue for tar?

**Comment by buanet** [comment]
Can you verify that this is the issue or is it just a "maybe"? As I am not able to test your theory at the moment I can't say anything about that.
As this issue originally was about checking and changing the file permissions please open a new one if you want to discuss the initial restore and have some facts to compare both methods. Thank you. 

Regards,
André
