### ISSUE TITLE
How to handle dynamic ports used by Adapters

### ISSUE THREAD

**Issue by Vrumfondel** [buanet/ioBroker.docker#178]
Hi there,
I just moved from an Rpi installation to a Docker install on my NAS - and face the following issue:

I got an adapter (knx), which after connecting to a gateway is listning on further input on an UDP port. Now, this port is changing on each start of the adapter, so I can't easily make an permanent port mapping to Docker.

So: How do I handle this - currently I can't get the adapter to work.

**Comment by fzzybllz** [comment]
you could go for the network options host or at least macvlan for the docker container.
In both cases you don't need to forward the ports to the container

**Comment by Apollon77** [comment]
The straight forward solution is to open feature request tickets on the affected adapters to allow to configure the port numbers, or ?!

**Comment by buanet** [comment]
I agree with @fzzybllz  and @Apollon77 . 
If you want to use dynamic ports you have to use a network option other than bridge. On the other hand it would be nice if dynamic port ranges could be set manually in adapter options.

I think there is no more to say. Could this be closed?

Regards,
André
