### ISSUE TITLE
Umstellung auf Redis per ENV - Migrierung Bestandsdaten

### ISSUE THREAD

**Issue by tugsi** [buanet/ioBroker.docker#179]
Wenn man ioBroker per `iobroker setup custom` von "files" auf "redis" umstellt, wird man gefragt, ob man die bestehenden Daten migireren möchte. (Bei Bestandssystem)
In den Docker ENV kann ich zwar angeben, dass ich jetzt Redis benutze, aber es geschieht keine Migration der Altdaten.
Somit werden die States neu aufgebaut, je nachdem welche Art von Skripten man hat, kann das zu Problemen führen, bis alle States wieder reingekommen sind.
Gerade bei Zigbee-Geräte werden nicht alle Daten (Battery etc.) ständig gesendet.

**Comment by buanet** [comment]
Wie erwähnt gab es das Feature noch nicht, als der Container Redis Support bekommen hat. Ich werde mir das bei Gelegenheit mal ansehen und schauen was man da schönes einbauen kann. 

MfG,
André

**Comment by buanet** [comment]
Moin,
ich hab mich mal ein bisschen mit dem Thema Redis Migration im Docker Container beschäftigt.
Meiner Meinung nach muss hier nichts gemacht werden. Ich sehe da zu wenig Anwendungsfälle. 

Was ich aber machen werde ist ein "Best Practices" Hinweis dazu. Die Migration ist nämlich denkbar simpel. 

Einfach im Container "iobroker setup custom" ausführen und die Einrichtung + Migration durchführen. Im Anschluss einfach den Container entsprechend mit den passenden Umgebungsvariablen starten und fertig. 
Denke dafür braucht es keine direkte Integration in den Container.

MfG,
André

**Comment by tugsi** [comment]
Moin,
nein es ist kein großes Thema, war ja aufgrund der Möglichkeit im ioBroker eine Frage. 
Also macht es Sinn erst "händisch" das im ioBroker zu machen, damit man eine Migration hat und dann im Anschluss die ENVs anpassen und Neustarten.
Sehr gut Idee, dass irgendwo zu vermerken, damit es jeder auch dann weiß.
Danke für Deine üben.
Gruß
Thomas
