### ISSUE TITLE
Question: New ioBroker Docker-Image for Synology with admin5 adapter

### ISSUE THREAD

**Issue by RkcCorian** [buanet/ioBroker.docker#183]
Hello @buanet,

I use your ioBroker container v5.1.0 on Synology Docker. In the meantime I would like to update the ioBroker admin adapter from 4.2.2 to the official 5.1.23. This is not working because of outdated js-controller. Will you provide a never Docker-Image in the near future or would do you suggest?!

Many many thanks!
Markus

**Comment by buanet** [comment]
Hello Markus,
a new Image won't solve your problem. As the js-controller is located in your iobroker folder, a docker image update will not update the js-controller. You have to upgrade it by yourself.
If you are german, check this to get some more information: https://smarthome.buanet.de/2020/10/iobroker-docker-container-updates-upgrades/

If this solves your problem. please close this issue. Thx.

Regards,
André

**Comment by RkcCorian** [comment]
Hi André,

vielen Dank für Deine Antwort. Ok, ich ging davon aus, dass ein neues Docker-Image auch einen neuen js-controller mitbringt. Würde es aber auch so versuchen... ich habe Deine Anleitung gelesen, allerdings habe ich bislang "nur" den simple terminal adapter verwendet. Mit "pkill -u iobroker" geht der verständlicherweise nicht mehr.
Hatte gegoogelt und dann versucht mit ssh admin@<IP> -p <Port> auf meinen ioBroker (auf der Synology) zuzugreifen, leider auch erfolglos ("kex_exchange_identification: Connection closed by remote host"). Nun weiß ich nicht, wie ich auf die Console meines ioBrocker in Docker auf meiner Synology komme um die von Dir genannten Befehle ausführen zu können. Hast Du hier noch einen Tipp?

Vielen Dank im Voraus!
Markus

**Comment by buanet** [comment]
Hallo Markus,
du kannst die Konsole des Containers direkt über die Docker Web UI der Disk Station öffnen. Heißt dort glaube ich Terminal. Falls du Portainer verwendest geht es natürlich auch dort.... Falls du es nicht findest, könnte ich dir heute Abend einen Screenshot machen...

MfG,
André

**Comment by RkcCorian** [comment]
Hallo André,

vielen Dank! Aufgrund Deiner Rückmeldung habe ich mir das Docker Terminal nochmal angeschaut. Was mir nicht klar war... ich musste erst explizit auf "Erstellen" klicken. Ich habe es immer direkt in das erste erstelle eingegeben, dass hat aber nie reagiert.
Jetzt hat es geklappt. Vielen Dank!!!

Viele Grüße!
Markus
