### ISSUE TITLE
Multihost slave will not start

### ISSUE THREAD

**Issue by stsch83** [buanet/ioBroker.docker#184]
Hello,

i try to create an docker swarm cluster with multihosts on each node. 
The master starts fine and looks very good. 
For testing i start the slave on the same node as the master. So, the slave will not start. 

This the log from the slave:

------------------------------------------------------------

---------------     2021-08-16 21:09:33      ---------------

------------------------------------------------------------

 

------------------------------------------------------------

-----       Welcome to your ioBroker-container!        -----

-----          Startupscript is now running.           -----

-----                Please be patient!                -----

------------------------------------------------------------

 

------------------------------------------------------------

-----              Debugging information               -----

-----                                                  -----

-----                      System                      -----

-----               arch:      aarch64                 -----

-----                                                  -----

-----                     Versions                     -----

-----               image:     v5.1.0                  -----

-----               node:      v12.22.2                -----

-----               npm:       6.14.13                 -----

-----                                                  -----

-----                       ENV                        -----

-----               IOB_MULTIHOST: slave                   -----

-----               IOB_OBJECTSDB_HOST: 192.168.65.131          -----

-----               IOB_OBJECTSDB_PORT: 10001                   -----

-----               IOB_OBJECTSDB_TYPE: file                    -----

-----               SETGID:    1000                    -----

-----               SETUID:    1000                    -----

-----               IOB_STATESDB_HOST: 192.168.65.131          -----

-----               IOB_STATESDB_PORT: 10000                   -----

-----               IOB_STATESDB_TYPE: file                    -----

------------------------------------------------------------

 

------------------------------------------------------------

-----         Step 1 of 5: Preparing container         -----

------------------------------------------------------------

 

Registering maintenance script as command.

Done.

 

------------------------------------------------------------

-----   Step 2 of 5: Detecting ioBroker installation   -----

------------------------------------------------------------

 

Existing installation of ioBroker detected in /opt/iobroker.

 

------------------------------------------------------------

-----   Step 3 of 5: Checking ioBroker installation    -----

------------------------------------------------------------

 

(Re)Setting folder permissions (This might take a while! Please be patient!)...

Done.

 

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...

Done.

 

------------------------------------------------------------

-----      Step 4 of 5: Applying special settings      -----

------------------------------------------------------------

 

Some adapters have special requirements/ settings which can be activated by the use of environment variables.

For more information take a look at readme.md on Github!

 

Multihost is set as "slave" by ENV and external objects db is set.

Skipping this step...

Done.

 

Multihost is set as "slave" by ENV and external states db is set.

Skipping this step...

Done.

 

ENV IOB_OBJECTSDB_TYPE is set and value meets detected ioBroker installation. Nothing to do here.

ENV IOB_OBJECTSDB_HOST is set and value meets detected ioBroker installation. Nothing to do here.

ENV IOB_OBJECTSDB_PORT is set and value meets detected ioBroker installation. Nothing to do here.

 

ENV IOB_STATESDB_TYPE is set and value meets detected ioBroker installation. Nothing to do here.

ENV IOB_STATESDB_HOST is set and value meets detected ioBroker installation. Nothing to do here.

ENV IOB_STATESDB_PORT is set and value meets detected ioBroker installation. Nothing to do here.

 

------------------------------------------------------------

-----          Step 5 of 5: ioBroker startup           -----

------------------------------------------------------------

**Comment by buanet** [comment]
Hi, 
I'm sorry. I see no way to investigate what's wrong in your case.
Way too less information about your setup (network, configurations, ip addresses). First thing I see is that your db ports are not coming with their default values... I think your slave does not get a connection to the databases...
As I think there might be no issue with the docker image itself, you better should try to get some support at the ioBroker Forum or Discord Channel. 

Regards,
André

**Comment by stsch83** [comment]
Hi, 

this is my stack file. 

version: '3.7'

volumes:
  iobroker_master:
  iobroker_slave1:

networks:
  myhost:
    name: host
    external: true

services:
  iobroker_master:
    image: buanet/iobroker:latest
    environment:
      - AVAHI=true
      - IOB_ADMINPORT=8081
      - IOB_MULTIHOST=master
      - IOB_OBJECTSDB_HOST=192.168.65.131
      - IOB_OBJECTSDB_PORT=10001
      - IOB_OBJECTSDB_TYPE=file
      - IOB_STATESDB_HOST=192.168.65.131
      - IOB_STATESDB_PORT=10000
      - IOB_STATESDB_TYPE=file
    volumes:
      - iobroker_master:/opt/iobroker
    networks:
      myhost: {}
      
  iobroker_slave1:
    depends_on: 
      - iobroker_master
    image: buanet/iobroker:latest
    environment:
      - IOB_MULTIHOST=slave
      - IOB_OBJECTSDB_HOST=192.168.65.131
      - IOB_OBJECTSDB_PORT=10001
      - IOB_OBJECTSDB_TYPE=file
      - IOB_STATESDB_HOST=192.168.65.131
      - IOB_STATESDB_PORT=10000
      - IOB_STATESDB_TYPE=file
    volumes:
      - iobroker_slave1:/opt/iobroker
    networks:
      myhost: {}


Is there any error? 

Everything starts fine, but the slave will not connect to the master.

**Comment by buanet** [comment]
I think it is not possible to run both (master and slave) on the **same host** with **host network** enabled.
As I see no use case for this, I've never tested it this way.
I think you have to test and investigate yourself if you could establish a connection to the filedb from slave to master.
Additionally, I`m not sure if changing the default statesdb and objectdb ports is supported by ioBroker or you have to take the default values instead when using filedb.

Regards,
André

**Comment by Apollon77** [comment]
In fact it shloud work. basically you "just" need to set the hostmane for the slave to a "unique" value different from master/real-hostname and provide the ip and port of db from master (even if this is 127.0.0.1). Only the hostname matters. Hostname can be set in config in iobroker-data/iobroker.json

**Comment by Apollon77** [comment]
Also the ports of the DB are completely configurable to any port you want

**Comment by stsch83** [comment]
it seams, that it is not working on the same host. now i have it on different hosts and it works

**Comment by buanet** [comment]
As I see no use case for running master and slave on the same host and it is working on different hosts I will close this issue. 

Regards,
André
