### ISSUE TITLE
portainer console -> Permission denied

### ISSUE THREAD

**Issue by stsch83** [buanet/ioBroker.docker#185]
Hallo,

ich habe das Problem, das ich keine iobroker Kommandos innerhalb der bash vom Container absetzten kann. ich bekomme immer Permission denied. Der admin Adapter ist allerdings über 8081 erreichbar und die Installation scheint auch erfolgreich durchlaufen worden sein. Irgendeine Idee was das Problem ist.

**Comment by stsch83** [comment]
> Hast du auch den Wartungsmodus mit dem Befehl "maintenance on" eingeschaltet?

natürlich nicht! :-( Hab es aber gerade damit probiert. Das selbe Problem. iobroker status -> Permission denied.

:-(

**Comment by buanet** [comment]
@stsch83 Wie greifst du auf die Konsole des Containers zu? Hast du Logs oder Screenshots? 
So ganz ohne geht Analyse halt nicht... 

MfG,
André

**Comment by stsch83** [comment]
> @stsch83 Wie greifst du auf die Konsole des Containers zu? Hast du Logs oder Screenshots?
> So ganz ohne geht Analyse halt nicht...
> 
> MfG,
> André

Hallo Andre, 
ich öffne die Konsole innerhalb von Portainer (/bin/bash) als root User. Das Volume für den Container liegt auf meiner Synology NAS welches per NFS eingebunden ist. Das Verzeichnis hat die Rechte 777 (ich weiß, ist nicht ideal). Fehlermeldungen aus dem Container gibt es nicht. Nur innerhalb der Konsole bekomme ich bei jedem iobroker Befehl "Permission denied".
Ich hoffe das hilft weiter.

**Comment by stsch83** [comment]
![2021-09-02_20-36-16](https://user-images.githubusercontent.com/40358350/131898351-fb999d8b-fe86-454a-adad-05ce98073855.jpg)

**Comment by winnyschuster** [comment]
probiere mal ./iobroker status. Wenn das funktioniert dann wirf iobroker aus /usr/bin raus

**Comment by stsch83** [comment]
> probiere mal ./iobroker status. Wenn das funktioniert dann wirf iobroker aus /usr/bin raus

Das funktioniert leider auch nicht

**Comment by buanet** [comment]
@stsch83 Mach mal im iobroker Ordner ein `ls -al` und poste den Output. 
Außerdem kannst du mal versuchen in dem Ordner eine Datei an zu legen. 
Du hast irgendwo ein Rechteproblem. 

> Das Volume für den Container liegt auf meiner Synology NAS welches per NFS eingebunden ist. 

Wie hast du den iobroker Ordner eingebunden? Hat der vielleicht nur Leseberechtigung im Container?

Kann es auch das "NOEXEC" Problem sein? 
https://github.com/buanet/ioBroker.docker/issues/28#issuecomment-505725906

MfG,
André

**Comment by stsch83** [comment]
> @stsch83 Mach mal im iobroker Ordner ein `ls -al` und poste den Output.
> Außerdem kannst du mal versuchen in dem Ordner eine Datei an zu legen.
> Du hast irgendwo ein Rechteproblem.
> 
> > Das Volume für den Container liegt auf meiner Synology NAS welches per NFS eingebunden ist.
> 
> Wie hast du den iobroker Ordner eingebunden? Hat der vielleicht nur Leseberechtigung im Container?
> 
> Kann es auch das "NOEXEC" Problem sein?
> [#28 (comment)](https://github.com/buanet/ioBroker.docker/issues/28#issuecomment-505725906)
> 
> MfG,
> André

Hallo Andre,

ich habe den Ordner wie folgt über die fstab eingebunden:
192.168.65.200:/volume1/backup/IoT_Stack/Container /mnt/nfs nfs auto,user,defaults,tcp,intr 0 0

![2021-09-08_09-44-33](https://user-images.githubusercontent.com/40358350/132468503-711e4cd2-b841-4c6e-aa38-c97ea754c4e5.jpg)

Das Anlegen des Ordners hat funktioniert. Siehe Screenshot.
![2021-09-08_09-46-41](https://user-images.githubusercontent.com/40358350/132468540-8d6ee914-e000-445f-afae-0d9902a18f74.jpg)

**Comment by buanet** [comment]
Kannst du mal den mount des Verzeichnisses prüfen. Nicht dass der das noexec flag hat, auch wenn es im fstab nicht angegeben ist
(https://unix.stackexchange.com/questions/37980/partition-mounted-noexec-even-though-not-specified-in-etc-fstab)

**Comment by stsch83** [comment]
> Kannst du mal den mount des Verzeichnisses prüfen. Nicht dass der das noexec flag hat, auch wenn es im fstab nicht angegeben ist
> (https://unix.stackexchange.com/questions/37980/partition-mounted-noexec-even-though-not-specified-in-etc-fstab)

├─/mnt/nfs                            192.168.65.200:/volume1/backup/IoT_Stack/Container
│                                                            nfs     rw,nosuid,n

????????????

**Comment by buanet** [comment]
Sorry, mehr fällt mir da nicht ein.

**Comment by stsch83** [comment]
ok danke

**Comment by buanet** [comment]
Hast du eigentlich mal versucht einen Container ohne gemountetes Verzeichnis zu starten? Wenn das geht, dann liegt es am mount. 
Eventuell mal nach den Rechten schauen. Weiß leider nicht im Detail wie das bei NFS mit ren Rechten ist, aber du könntest da ein problem mit dem UID/GID mapping haben. ggf. musst du als Umgebungsvariable eine UID/ GID angeben, die die richtigen Rechte (rwx) auf dein NFS Share hat...

MfG,
André

**Comment by buanet** [comment]
@stsch83 Da ich seit drei Wochen nichts mehr von dir gehört habe schließe ich den Issue. 
Wenn noch Fragen sind, melde dich. 

MfG,
André

**Comment by stsch83** [comment]
> Hallo,
> 
> ich habe gerade das selbe Problem. Der iobroker-container wurde frisch aktualisiert, und `maintenance on` klappt noch, `iobroker update` wirft aber ein permission denied raus. Der Container läuft auf meinem Server und als permanentes Verzeichnis ist ein Ordner auf dem Server angegeben - also kein NFS. Der Ordner hat mitlerweile auch (rekusriv) für alle und jeden sämtliche Berechtigungen erhalten.
> 
> Was kann ich denn noch tun?

Ich kann dir nur soviel sagen, bei mir war das Problem, dass beim Mount in /etc/fstab kein "exec" angeben war.

**Comment by quotschmacher** [comment]
@stsch83 wie geschrieben: bei mir ist es kein nfs oder sonstiges, sondern der iobroker container läuft lokal auf meinem omv server

**Comment by quotschmacher** [comment]
> Kann es sein, dass dein Verzeichnis-Pfad zu lang ist.

das habe ich ausgeschlossen - bin ja nicht unter windows unterwegs. allerdings habe ich es dann doch mal unter `/usr` getestet und da ging es. habe ich also mal ein bisschen nachgeforscht - openmediavault mounted standardmäßig alle laufwerke mit `noexec`... das war es also doch!

fix für andere mit dem problem und omv 5

```
nano /etc/openmediavault/config.xml
```
dort dann den `<fstab>`-abschnitt suchen und unter `<mtent><opts>` für die entsprechende platte den `noexec`-Eintrag entfernen. Anschließend

```
omv-salt deploy run fstab
```

und das System neu starten.
