### ISSUE TITLE
After restore in container with new hostname - ioBroker not running/ admin not accessible 

### ISSUE THREAD

**Issue by buanet** [buanet/ioBroker.docker#188]
At the moment there seems to be an issue when restoring on a new Docker container with a different hostname. 
After restart of the container the log says something like:
```
--------------------------------------------------------------------------------,
-----                    Step 5 of 5: ioBroker startup                     -----,
--------------------------------------------------------------------------------,
Starting ioBroker...,
================================== > LOG REDIRECT system.adapter.admin.0 => true [starting],
host.iobrokerold check instance "system.adapter.admin.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.javascript.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.backitup.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.discovery.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.dwd.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.history.0" for host "iobrokernew"
```

This seems to be an issue in ioBroker restoring procedure. I already opened an issue in ioBroker js-controller repo:
https://github.com/ioBroker/ioBroker.js-controller/issues/1450

This issue is for documentation only. For workaround see next post.

Regards,
André

**Comment by buanet** [comment]
Known workaround:

To get ioBroker working after a restore, you have to call `iobroker host [oldhostname]` at the containers command line. Make sure you stopped ioBroker before. Here is an example: 
```
root@iobrokernew:/opt/iobroker# pkill -u iobroker
root@iobrokernew:/opt/iobroker# iobroker host iobrokerold
Host "iobrokerold" successfully renamed to "iobrokernew".
No instances found for host "iobrokerold"!
root@iobrokernew:/opt/iobroker# 
```
When using a singlehost you can use `iobroker host this` instead of `iobroker host [oldhostname]`.
Don't use `iobroker host this` when using multhost (master/slave) system. For details see this [link](https://github.com/ioBroker/ioBroker/wiki/Console-commands#iobroker-host).

If you have any questions feel free to comment. Thank you.

Regards,
André

**Comment by buanet** [comment]
Short update:
An official  solution for this is confirmed for js-controller 4.0.x (for details see links above).
This issue remains open for documentation purpose until the fix will be available in a stable version. 

Regards,
André

**Comment by Curtis777** [comment]
I tried the fix,
A host with the name "iobroker old" Allready exists.
Is the only answer I got....
I also tried to find a solution in the discord channel  (German iobroker - docker)

**Comment by buanet** [comment]
This seems still a problem in some way. Opened an issue at iobroker.js-controller.
https://github.com/ioBroker/ioBroker.js-controller/issues/2241

**Comment by buanet** [comment]
This should be fixed with js-controller v5. The issue will remain open until js-controller v5 release for documentation of the workaround.

**Comment by buanet** [comment]
My last test showed that this is no longer a problem.
