### ISSUE TITLE
ENV are ignored

### ISSUE THREAD

**Issue by netzbus** [buanet/ioBroker.docker#191]
I need to define diffrent DB Ports because of host network. 
After setting DB Ports with ENV and creating the container, they are silently ignored

**Comment by buanet** [comment]
I see no report of an issue. Feel free to reopen and try again.

**Comment by netzbus** [comment]
Haha, this is your way of solving Issues? Nice try

**Comment by buanet** [comment]
If you would know me, you would know how much time I spend helping other with their issues... so please be careful with what you are writing here... Supporting YOU is my spare time... please don't forget this!

This here is no chat or forum. If you think you found an issue you have to provide as much information you could to give me a chance to reproduce it. If you are not willing or able to do so, please refer to [ioBroker forum](https://forum.iobroker.net/) or ioBroker [Discord channel](https://discord.gg/HwUCwsH). 

As I wrote: Feel free to reopen this issue with "as much information you could to give".

Regards,
André
