### ISSUE TITLE
Package libraspberrypi-bin

### ISSUE THREAD

**Issue by ChrizZz90** [buanet/ioBroker.docker#192]
I try to install the libraspberrypi-bin package to use the raspberry pi info adapter, but I get:

```
root@iobroker:/opt/iobroker# sudo apt-get install libraspberrypi-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libraspberrypi-bin
```

I can use ENV Packages or try it manually, I still get this error.

The goal behind installing libraspberrypi-bin is to get access to vcgencmd, because my logs are complaining:

`/bin/sh: 1: vcgencmd: not found`

Any idea what kind of mistake I make?

**Comment by Apollon77** [comment]
Is that package libraspberrypi-bin located in the officialDebuan repos at all? I guess not. I'm also not sure if this will work at all in docker container

**Comment by buanet** [comment]
There is no mistake. 
The Docker image is based on Debian Bullseye. The package you are requesting is not available for this Linux-distribution. 

You may ask google for something like "installing vcgencmd on debian/ bullseye". It might be possible that there is a way to get in running by self compiling it... But this may only help you if you are at least an Linux advanced user.

If that answers your question, feel free to close this issue. 
Thank you. 

Regards,
André

**Comment by ChrizZz90** [comment]
alright, thanks for that. I will leave it as it is and close this issue.
