### ISSUE TITLE
iobroker startet nicht

### ISSUE THREAD

**Issue by DiTechRacer** [buanet/ioBroker.docker#199]
Moin,

ich habe mit dem image buanet/iobroker:latest über Portainer einen Container erstellt.
Allerdings startet er nicht und bringt folgendes in der Log.
Das ganze läuft auf einem Pi 4 8GB mit Raspian OS 32bit
Kann mir jemand helfen?

LG Tim

Bei Step 3: 

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...,
cp: preserving times for '/opt/iobroker/iobroker.bak': Operation not permitted,
Done.,
 ,
terminate called after throwing an instance of 'std::length_error',
  what():  basic_string::_M_replace_aux,
iobroker: line 6:   292 Aborted                 gosu iobroker node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js "$@",
/opt/scripts/iobroker_startup.sh: line 199: [: !=: unary operator expected,

Bei Step 5:

 ,
Starting ioBroker...,
 ,
terminate called after throwing an instance of 'std::length_error',
  what():  basic_string::_M_replace_aux,
/opt/scripts/iobroker_startup.sh: line 505:   313 Aborted                 gosu iobroker node node_modules/iobroker.js-controller/controller.js,
tail: cannot read realtime clock: Operation not permitted

**Comment by buanet** [comment]
Wie hast du den ioBroker Ordner eingebunden? Ich würde auf permission issue tippen.

MfG,
André

**Comment by DiTechRacer** [comment]
Sehe das auch so das da ein Rechteproblem besteht. Ich hab kein Volume eingebunden. Ich weiß, entgegen deiner Anleitung. Aber ich hatte heute Mittag noch einen Container laufen. Also ioBroker. Hab den Container aber gelöscht weils ein Update gab. Hatte ein Backup von iobroker und dachte ich kanns im neuen Container einfach restoren. Aber der neue Container funktioniert nicht mehr.. Bin echt Ratlos..

**Comment by buanet** [comment]
Heißt du hast kein mount sondern alles im Container? Dann müsste es gehen... Die Rechte Probleme kommen eigentlich immer davon, wenn man den Ordner einbindet...
Hast du mal die alte Version (v5.1.0) probiert? Habe gerade keinen Pi startklar, kann also nicht sagen ob das ARM Image in der neusten Version wirklich funktioniert... Bis jetzt habe ich dazu aber nichts gehört....

MfG,
André

**Comment by DiTechRacer** [comment]
Wie bekomme ich das 5.1 image? Hast du nen Link?

LG Tim

**Comment by buanet** [comment]
Wie startest du den Container? Kommandozeile oder Portainer? 
Die vorherige Version bekommst du, wenn du statt des Tags `latest` einfach die Version `v5.1.0` verwendest.
Das sind allerdings Docker Basics...

Falls du Unterstützung benötigst kann ich dir nur den [ioBroker Discord Channel]( https://discord.gg/HwUCwsH) empfehlen (falls du da noch nicht unterwegs bist). Da lesen mehr Leute die Fragen mit und du bekommst ggf. auch eine Antwort wenn ich gerade dabei bin den Garten winterfest zu machen. ;) 

MfG,
André

**Comment by buanet** [comment]
Kleines Update: 
Habe mir gerade mal meinen Pi zum Testen aufgesetzt. Das arm32v7 Image scheint in der Tat "broken" zu sein. :)  
Dein Workaround wäre also den v5.1.0 Tag zu verwenden (da geht es noch). 
Habe auch eine Vermutung was da falsch ist. Arbeite an einem Fix. 

MfG,
André

**Comment by buanet** [comment]
Und noch ein Update hinterher: 
Habe jetzt gefunden wo es klemmt. Offenbar funktioniert das Ganze auf der arm Architektur (Raspberry pi und co) aktuell nur wenn der Container `privileged` ausgeführt wird.

Portainer: 
![image](https://user-images.githubusercontent.com/16137672/135729137-f59a1b2b-b2e4-47ec-9a35-d5cf672d21b8.png)

Konsole: 
`--privileged`

Irgendwo gibt es ein Zugriffsproblem. Details habe ich noch nicht, aber das wäre auf jeden fall ein workaround...

MfG,
André

**Comment by buanet** [comment]
Ok, jetzt habe ich die Ursache gefunden. 
Offenbar gibt es aktuell generell Probleme damit einen auf Debian Bullseye basierenden Container auf arm Architekturen auszuführen (Hat was mit der Hardwareclock zu tun).
Ursache ist die Version von `libseccomp2`. Diese ist für arm noch auf Version 2.3.3-4, muss aber > 2.4 sein damit es klappt.  
Unter Raspbian kann man die Version manuell wie folgt updaten:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```
Der Workaround über das Ausführen des Containers mit erweiterten Rechten entfällt dann natürlich wieder. 

Es handelt sich hier um ein "Problem" des Betriebssystems des Host und nicht um einen Fehler im Docker Image.  

Bitte mal testen. Wenns klappt Issue schließen.

MfG,
André

**Comment by andreas-vester** [comment]
Bei mir funktioniert das Update leider nicht wie erwartet. Hier mal der exakte Auszug aus dem Terminal, wenn ich deine vier Befehle nacheinander eingebe.

```
pi@iobrokerSlave:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
Executing: /tmp/apt-key-gpghome.JPr8jXYGCw/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.JPr8jXYGCw/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $ echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
deb http://deb.debian.org/debian buster-backports main
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $ sudo apt update
Hit:1 https://download.docker.com/linux/raspbian stretch InRelease
Get:2 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Hit:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:4 http://archive.raspberrypi.org/debian stretch InRelease
Err:2 http://deb.debian.org/debian buster-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9E: The repository 'http://deb.debian.org/debian buster-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:2
W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:2
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:3
W: Target Translations (main/i18n/Translation-en_GB) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/buster-backports.list:1 and /etc/apt/sources.list.d/buster-backports.list:3
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $
pi@iobrokerSlave:~ $ sudo apt install -t buster-backports libseccomp2
Reading package lists... Done
E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources
pi@iobrokerSlave:~ $
```

**Comment by buanet** [comment]
@andreas-vester 
Bitte mal Google fragen warum bei dir schon der erste Schritt fehlschlägt...
```
pi@iobrokerSlave:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
Executing: /tmp/apt-key-gpghome.JPr8jXYGCw/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.JPr8jXYGCw/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

**Comment by DiTechRacer** [comment]
Hey André,

danke dir! Ich teste es morgen und berichte.

LG Tim

**Comment by andreas-vester** [comment]
> 
> 
> @andreas-vester Bitte mal Google fragen warum bei dir schon der erste Schritt fehlschlägt...
> 
> ```
> pi@iobrokerSlave:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> Executing: /tmp/apt-key-gpghome.JPr8jXYGCw/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
> gpg: connecting dirmngr at '/tmp/apt-key-gpghome.JPr8jXYGCw/S.dirmngr' failed: No such file or directory
> gpg: keyserver receive failed: No dirmngr
> ```
> 
> [EDIT] Kleiner Service von mir: [hier lang](https://www.google.com/search?q=failed+to+start+the+dirmngr+%27%2Fusr%2Fbin%2Fdirmngr%27%3A+No+such+file+or+directory&rlz=1C1CHBF_deDE954DE954&oq=failed+to+start+the+dirmngr+%27%2Fusr%2Fbin%2Fdirmngr%27%3A+No+such+file+or+directory&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8)
> 
> MfG, André

Hallo André,

mit deinem Hinweis hat es nun funktoniert. Vielen Dank!

Für alle, die das gleiche Problem haben, bitte folgende Befehle vorweg eingeben, um ``dirmngr`` zu installieren:

```
sudo apt update
sudo apt install dirmngr --install-recommends
```
