### ISSUE TITLE
Executeable of ping is missing in image

### ISSUE THREAD

**Issue by peterimnetz** [buanet/ioBroker.docker#200]
I installed the latest Docker image today and my ping adapter was not working - looks like executeable /bin/ping is missing in image. Is this intended?

**Comment by buanet** [comment]
Yes it is.

As we switched to base image `Debian Bullseye slim` with v5.2.0 the ping command is no longer pre installed by default. 
This step was made to keep the Image as small as possible. 

According to the [docs of the adapter](https://github.com/ioBroker/ioBroker.ping/blob/master/README.md#known-issues), it is necessary to have `iputils-ping` installed. To get this package installed please use the `PACKAGES` [environment variable](https://github.com/buanet/ioBroker.docker#environment-variables). 

If this solves your problem, please close the issue. 
Thank you,

Regards,
André

**Comment by peterimnetz** [comment]
Thank you for clarification. I'll close this issue.

**Comment by fs-plugins** [comment]
"Händisch kann ich es installieren, muss aber vorher "apt update" absetzen"

gleiches Problem hier...
kein Einwand gegen die Begründung - dann sollte jedoch das Zufügen von Paketen ähnlich wie bei Javascript ermöglicht werden, so dass derartige Konfigurationen nicht außerhalb des Systems notwendig sind
benötigte Pakete also innerhalb iobroker in der GUI eintragbar und bei Start von iobroker prüfen und ggf installieren+starten

**Comment by buanet** [comment]
@fs-plugins Vielen Dank für dein Feedback. 

Damit hier nicht gleich wieder eine Diskussion über standardmäßig im Image enthaltene Pakete los geht hier einmal ein paar Fakten zum Thema:

1. Das Docker Image ist nicht gleich ioBroker, sondern eher zu vergleichen mit einem virtuellen Raspberry Pi auf dem ioBroker bereits vorinstalliert ist (das ist allerdings technisch nicht 100% korrekt!). Wie beim Pi (oder anderen Systemen auch) müssen für einige Adapter Linux Pakete nachinstalliert werden. Diese sind in der Regel in der Adapter Beschreibung aufgeführt. 

2. Docker Container sind NICHT dazu gemacht dort händisch Software nach zu installieren oder darin Updates zu machen. Um Updates zu machen wird in der Regel eine neue Version des Images geladen. Damit die nach installierten Pakete auch bei einem Recreate des Containers mit einer neuen Image Version erhalten bleiben gibt es 

3. Die [Umgebungsvariable "PACKAGES"](https://github.com/buanet/ioBroker.docker#environment-variables). Hier kommen alle Linux Pakete rein, die von Adaptern benötigt werden die nicht zu einer Standardinstallation gehören (z.B. der Ping-Adapter). Umgebungsvariablen sind KEINE "derartige Konfiguration [...] außerhalb des Systems" sondern Teil des Prozesses einen Docker Container aufzusetzen. Die ENV "PACKAGES" gibt es weil sicherlich niemand Lust hat

4. ...bei jedem Update ein mehrere GB großes ioBroker Docker Image herunter zu laden, nur weil darin ALLE Pakete enthalten sind die irgendein Adapter ggf. benötigt (egal ob installiert oder nicht). 

Und hier der wichtigste Fakt, der zumindest für den Ping Adapter die Diskussion beenden sollte:

5. Glücklicherweise (für alle Ping-Fans) ist der Discovery-Adapter ein "default-Adapter". Dieser arbeitet ebenfalls mit dem ping Befehl. Daher wird in der kommenden Version auch wieder das entsprechende Paket im Container erhalten sein!

In eigener Sache: Das Verschwinden der Ping-Funktion ist nicht mit böser Absicht geschehen! Es resultiert aus dem Wechsel auf ein neues Base Image für den Container. Bei "Bullseye" ist es nun leider nicht mehr von Haus aus dabei. Damit so etwas nicht wieder passieren kann, lade ich alle herzlich ein regelmäßig meine Beta-Versionen zu testen! Ich selbst kann nicht alle Adapter im Blick behalten und vor einem Release testen. Dazu benötige ich die Community. In diesem konkreten Fall ist es halt offenbar niemandem aufgefallen.... oder es hat sich halt schlicht niemand für den Betatest zuständig gefühlt...

> dann sollte jedoch das Zufügen von Paketen ähnlich wie bei Javascript ermöglicht werden, so dass derartige Konfigurationen nicht außerhalb des Systems notwendig sind
> benötigte Pakete also innerhalb iobroker in der GUI eintragbar und bei Start von iobroker prüfen und ggf installieren+starten
> 
> Nachtrag:
> oder aber bei Installation/Aktualisierung von Adaptern muss eine Abhängigkeitsfunktion mit der Nachlademöglichkeit entsprechender Pakete bzw. mindestens einer autom. Deaktivierung derer eingeführt werden

Das ist eine Diskussion mit der du bei diesem geschlossenen Issue komplett falsch bist. Das musst du mit den Adapter-Entwicklern besprechen. Technisch ist eine solche "Nachlademöglichkeit" bei npm Paketen gut machbar, bei Linux-(System-)Paketen sieht das etwas anders aus. Verschiedene Betriebssysteme ist da nur ein Stichwort.... 

> es ist einfach nicht sinnvoll, wenn bisher laufende Adapter/Funktionen/Scripte auf diese Weise einfach nur noch unentwegt Error's werfen

Was erwartest du? Die Fehlermeldung hat dich immerhin hier her geführt und es dir ermöglicht den Fehler zu beheben. Wenn du mehr erwartest lies bitte nochmal den Absatz der mit "In eigener Sache" beginnt.
Ich freue mich dich dann zukünftig als Betatester zu begrüßen. Aktuelle Infos und Support zu Beta Versionen findest du im [ioBroker Discord Channel](https://discord.gg/HwUCwsH) unter "BETA TESTING & FEEDBACK" >  docker-image. Oder schaue einfach mal so im Sprachchat vorbei. Bin da regelmäßig online, dann kann ich dir vielleicht meine Seite mal etwas näher bringen. :)

MfG,
André

**Comment by fullcavediver** [comment]
> "Händisch kann ich es installieren, muss aber vorher "apt update" absetzen"
> 
> gleiches Problem hier... kein Einwand gegen die Begründung - dann sollte jedoch das Zufügen von Paketen ähnlich wie bei Javascript ermöglicht werden, so dass derartige Konfigurationen nicht außerhalb des Systems notwendig sind benötigte Pakete also innerhalb iobroker in der GUI eintragbar und bei Start von iobroker prüfen und ggf installieren+starten
> 
> Nachtrag: oder aber bei Installation/Aktualisierung von Adaptern muss eine Abhängigkeitsfunktion mit der Nachlademöglichkeit entsprechender Pakete bzw. mindestens einer autom. Deaktivierung derer eingeführt werden
> 
> es ist einfach nicht sinnvoll, wenn bisher laufende Adapter/Funktionen/Scripte auf diese Weise einfach nur noch unentwegt Error's werfen

@fs-plugins, 

ich kann dich gut verstehen, ich habe mich die letzten Wochen auch geärgert, bis ich selbst darauf gekommen bin, dass man kein Einführungszeichen verwenden darf, wenn man nur ein Paket installieren möchte. Dann funktioniert es und man braucht kein `apt update` davor absetzen. Diese Meldung ist echt Irreführend und man findet keinen Hinweis darauf in dem Forum - ich habe zumindest nichts gefunden.

**Comment by fs-plugins** [comment]
@buanet 

zuerst einmal recht vielen Dank, dass du dir dermaßen viel Mühe mit Erklären und Begründen gegeben hast - und wie von mir erwähnt verstehe ich ja auch die (gut gemeinte) Absicht dahinter

und natürlich habe ich auch gedacht, na gut dann setze ich eben den Parameter - dummerweise (hat absolut nichts mit dem hier zu tun) funktioniert, nachdem ich bereits seit langem samba im Portainer-ENV gesetzt habe, ein zweites Paket zusätzlich nicht (oder möglicherweise genau dieses nur nicht)
mir persönlich geht es übrigens nichtmal um den Discovery, ich nutze Ping hauptsächlich in eigenen Scripten von Anwesenheit bis Erkennung Geräte-/Verbindungsausfall, es war auch irgendein anderer Adapter noch der protestiert hatte
allerdings ist ja damit zu rechnen, das ich mich neben samba und ping früher oder später auch um andere Pakete selbst kümmern muss, da braucht es eben eine gut händelbare Möglichkeit

>>Verschiedene Betriebssysteme ist da nur ein Stichwort....
stimmt, habe ich nicht bedacht...
>>sondern Teil des Prozesses einen Docker Container aufzusetzen
auch damit fallen meine Denkansätze hinten runter

>>Ich freue mich dich dann zukünftig als Betatester zu begrüßen
der war gut ;-) ist aber leider so, dass ich für meine eigenen freeware-Progs keine Betatester habe und dort viel Zeit investiere
auch und geade deshalb ist mir auch klar wie so etwas passieren kann (und früher oder später sogar muss), mir sind die Dinge mehr als zu gut bekannt

nochmal - toll dass du dich so ausführlich mit meinem Kommentar auseinandergesetzt hast (auch sowas frisst Zeit), vielen Dank dafür

**Comment by buanet** [comment]
@fs-plugins 

> Ist aber leider so, dass ich für meine eigenen freeware-Progs keine Betatester habe und dort viel Zeit investiere
> auch und geade deshalb ist mir auch klar wie so etwas passieren kann (und früher oder später sogar muss), mir sind die Dinge mehr als zu gut bekannt

Das ist genau das worum es geht. Dann weißt du auch warum ich darauf so reagiere. Es gibt hier immer wieder solche Diskussionen und die Leute verstehen meist nicht dass man viel Zeit investiert. Hauptsache es wird gemeckert... Deswegen lade ich in solchen Situationen die Leute grundsätzlich zum Mitmachen ein. :)

> dass du dir dermaßen viel Mühe mit Erklären und Begründen gegeben hast

Das hat gar nicht mal was mit dir zu tun, sondern mit der Tatsache dass ich alle paar Wochen eine Diskussion darüber führe ob ein Paket, welches für Adapter X benötigt wird in das Image einbaue. Den Post habe ich so ausführlich gemacht um in kommenden Diskussionen einfach darauf verweisen zu können. ;)

> dummerweise (hat absolut nichts mit dem hier zu tun) funktioniert, nachdem ich bereits seit langem samba im Portainer-ENV gesetzt habe, ein zweites Paket zusätzlich nicht (oder möglicherweise genau dieses nur nicht)

Das hingegen ist wieder für mich wichtiges Feedback. Wenn es bei dir so ist, dass keine zwei Pakete zusammen funktionieren (müssen mit Leerzeichen getrennt sein) dann ist das eine wichtige Info für mich. Dazu dann bitte eine Issue mit Logfile erstellen. Vorher aber über die Kommandozeile prüfen ob sich die Pakete händisch installieren lassen, die Schreibweise korrekt ist bzw. diese Pakete überhaupt für Debian Bullseye zur Verfügung stehen.  

> mir persönlich geht es übrigens nichtmal um den Discovery

Das hast du glaube ich falsch verstanden. :) Der Discovery Adapter ist ein Adapter der standardmäßig im ioBroker installiert ist. Dieser benutzt ebenfalls den ping-Befehl. Und aus diesem Grund werde ich das beim Wechsel des Base Image abhanden gekommene Paket in der nächsten Version sowieso wieder standardmäßig einbauen. Auch wenn du den Discovery nicht benutzt wirst du als Ping-Nutzer also davon profitieren... 

> allerdings ist ja damit zu rechnen, das ich mich neben samba und ping früher oder später auch um andere Pakete selbst kümmern muss, da braucht es eben eine gut händelbare Möglichkeit

Besser händelbar als die ENV? Wüsste nicht wie das aussehen sollte. Wenn du magst schaue gerne mal im Discord vorbei. Ich kann dir dann an meinem Testsystem zeigen wie ich mit Hilfe von Stacks bzw. docker-compose ein zusätzliches Paket mit zwei Klicks hinzu füge. Den Rest macht Docker (oder falls du es nutzt Portainer) für dich.
Docker bzw. Portainer können dir das Leben an dieser Stelle unheimlich vereinfachen sofern man bereit ist sich mit der Materie auseinander zu setzen. Für Klick'n'go ist Docker einfach zu speziell...

MfG,
André

**Comment by fs-plugins** [comment]
Moin,
ich habe den Container im Portainer jetzt komplett neu angelegt, scheint nun zu funktionieren
möglicherweise (meine englisch-Kenntnisse reichen bei weitem nicht das alles vernünftig lesen zu können) kann ich bei der free-Version derartige Änderungen nicht per duplikate o.ä. machen

**Comment by fs-plugins** [comment]
Nachtrag/Aufklärung:
die Ursache für das Paketproblem ist eine Problematik im Synology-Docker, deshalb können die ENV-Umgebungsvariablen nicht geändert werden

parktikabelste Lösung für mich: im Portainer neuen Container erstellen mit den gleichen Einstellungen (inklusiver der gleichen Verzeichnis-mappings) und den gewünschten Umgebungsvariablen
