### ISSUE TITLE
Issues installing / running image on raspberry pi 4

### ISSUE THREAD

**Issue by zbigniewbednarek** [buanet/ioBroker.docker#208]
Hello,
I have try to install ioBroker as container on my raspberry pi 4. Unfortunately after issuing following command:
sudo docker run -p 8081:8081 --name iobroker -v iobrokerdata:/opt/iobroker buanet/iobroker:latest

I got:
Unable to find image 'buanet/iobroker:latest' locally
latest: Pulling from buanet/iobroker
4e5300249f84: Pull complete
5daa67d47531: Pull complete
889d6f93e65d: Pull complete
23d9d6b2bea7: Pull complete
a6b77c316f17: Pull complete
3c111d0f9116: Pull complete
e7d8be314f95: Pull complete
590f77dbe728: Pull complete
deda63a5e273: Pull complete
Digest: sha256:0c2cd737c7ce6eef89ebacb7bdb8891e4073e714cf9a378e009bd331234da1f6
Status: Downloaded newer image for buanet/iobroker:latest

--------------------------------------------------------------------------------
-------------------------     1970-01-01 01:00:00      -------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                 Welcome to your ioBroker-container!                  -----
-----                    Startupscript is now running.                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                        Debugging information                         -----
-----                                                                      -----
-----                                System                                -----
-----                    arch:                armv7l                       -----
-----                                                                      -----
-----                             Docker-Image                             -----
-----                    image:               v5.2.0                       -----
-----                    build:               2021-10-15T03:48:21+00:00    -----
-----                                                                      -----
-----                               Versions                               -----
-----                    terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux

node:                                             -----
-----                    terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux

npm:                                              -----
-----                                                                      -----
-----                                 ENV                                  -----
-----                    SETGID:              1000                         -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------

Updating Linux packages on first run...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
Done.

Registering maintenance script as command...
Done.

--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------

Existing installation of ioBroker detected in /opt/iobroker.

--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------

(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
cp: preserving times for '/opt/iobroker/iobroker.bak': Operation not permitted
Done.

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
iobroker: line 6:   182 Aborted                 gosu iobroker node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js "$@"
/opt/scripts/iobroker_startup.sh: line 199: [: !=: unary operator expected
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------

Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information take a look at readme.md on Github!

--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------

Starting ioBroker...

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
/opt/scripts/iobroker_startup.sh: line 505:   203 Aborted                 gosu iobroker node node_modules/iobroker.js-controller/controller.js
tail: cannot read realtime clock: Operation not permitted

Any clue what is wrong here ? Does this package supported on raspberry pi ?

**Comment by zbigniewbednarek** [comment]
My OS Version:
Linux raspberrypi 5.10.52-v7l+ #1440 SMP Tue Jul 27 09:55:21 BST 2021 armv7l GNU/Linux

 docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:38 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:31 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by zbigniewbednarek** [comment]
Upgraded to latest available os / docker versions - Unfortunatelly still the same issues:

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
pi@raspberrypi:~ $ docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:06:55 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:04:47 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by buanet** [comment]
Hi,
seems to be the sam issue like #199. Please check this:
https://github.com/buanet/ioBroker.docker/issues/199#issuecomment-932918780

Regards,
André

**Comment by zbigniewbednarek** [comment]
Hello,
Thank you for pointing out the previous issue. It solved my problem as well. 

Regards,
Zbigniew
