### ISSUE TITLE
Update funktioniert nicht

### ISSUE THREAD

**Issue by dfoxg** [buanet/ioBroker.docker#212]
Ich versuche gerade den js-controller auf eine neue Version anzuheben. Dazu habe ich [hier](https://smarthome.buanet.de/2020/10/iobroker-docker-container-updates-upgrades/) folgende Kommandos gefunden:
```
pkill -u iobroker
iobroker update
iobroker upgrade self
```

Doch leider wirft der Befehl `iobroker update self` dann folgenden Fehler:
```
root@iobroker:/opt/iobroker# pkill -u iobroker
root@iobroker:/opt/iobroker# iobroker update
No connection to databases possible ...
 Cannot load "custom": Connection is closed.
 Cannot initialize database scripts: Cannot load "custom" into objects database: Connection is closed.
root@iobroker:/opt/iobroker# iobroker upgrade self
No connection to databases possible ...
 Cannot load "custom": Connection is closed.
 Cannot initialize database scripts: Cannot load "custom" into objects database: Connection is closed.
```

Kann mir hier jemand helfen?

**Comment by Apollon77** [comment]
Welcher js-controller ist installiert?

**Comment by dfoxg** [comment]
> Welcher js-controller ist installiert?

3.2.16 ist Installiert, möchte auf 3.3.18 updaten.

**Comment by Apollon77** [comment]
Bitte aus https://forum.iobroker.net/topic/46758/js-controller-3-3-jetzt-im-stable versuchen:

>Wichtig: Falls es mit js.controller 3.2.x bei update oder upgrade einen Fehler gibt "No connection to database" dann bitte nochmals versuchen, wenn wieder passiert folgende Schritte ausführen:

    Editiere /opt/iobroker/iobroker-data/iobroker.json
    Unter objects und states gibt es ein ' "connectTimeout": 2000,`
    Zahl ändern in 5000 draus.
    Neu versuchen
    Nach dem Upgrade am besten den Wert wieder zurücketzen weil der js-controller 3.3 hier optimiert und länger wartet

**Comment by dfoxg** [comment]
Ist durchgelaufen, danke dir!
