### ISSUE TITLE
Nach Aktualisierung Image auf V6.0.0 Probleme mit Ping-Adapter

### ISSUE THREAD

**Issue by SmartHomer0** [buanet/ioBroker.docker#221]
Hallo Andre,

ich habe grade für meine Docker-Installation ein Update gemacht:
Unter ENV-PACKAGES habe ich noch aus der bisherigen Installation die iputils-ping eingetragen (s. Screenshot)

![grafik](https://user-images.githubusercontent.com/90909896/145632949-fede87af-83f7-4057-9ab3-8718816e3a77.png)

Seit dem Update bringt der PING-Adapter Fehlermeldungen.
Ich habe ihn bereits de-installiert und wieder neu installiert, aber leider hat das auch nichts gebracht, nachfolgend der Debug-Log

`<html><body>

ping.0 | 5112 | 2021-12-10 20:35:53.610 | debug | Ping result for 192.168.1.27: false in -ms
-- | -- | -- | -- | --
ping.0 | 5112 | 2021-12-10 20:35:53.608 | debug | STDERR: /bin/ping: socket: Operation not permitted
ping.0 | 5112 | 2021-12-10 20:35:53.600 | debug | System command: /bin/ping -n -w 2 -c 1 192.168.1.27
ping.0 | 5112 | 2021-12-10 20:35:53.599 | debug | Pinging 192.168.1.27
ping.0 | 5112 | 2021-12-10 20:34:53.594 | debug | Ping result for 192.168.1.27: false in -ms
ping.0 | 5112 | 2021-12-10 20:34:53.587 | debug | STDERR: /bin/ping: socket: Operation not permitted
ping.0 | 5112 | 2021-12-10 20:34:53.577 | debug | System command: /bin/ping -n -w 2 -c 1 192.168.1.27
ping.0 | 5112 | 2021-12-10 20:34:53.575 | debug | Pinging 192.168.1.27
ping.0 | 5112 | 2021-12-10 20:34:53.574 | debug | Finished tasks of objects update
ping.0 | 5112 | 2021-12-10 20:34:53.572 | debug | Start tasks of objects update
ping.0 | 5112 | 2021-12-10 20:34:53.570 | debug | Prepare tasks of objects update
ping.0 | 5112 | 2021-12-10 20:34:53.513 | debug | Get existing objects
ping.0 | 5112 | 2021-12-10 20:34:53.510 | debug | Host=ioBrokerHW
ping.0 | 5112 | 2021-12-10 20:34:53.509 | debug | Prepare objects
ping.0 | 5112 | 2021-12-10 20:34:53.486 | info | starting. Version 1.5.0 in /opt/iobroker/node_modules/iobroker.ping, node: v14.18.2, js-controller: 3.3.21
ping.0 | 5112 | 2021-12-10 20:34:53.223 | debug | Plugin sentry Initialize Plugin (enabled=true)
ping.0 | 5112 | 2021-12-10 20:34:52.878 | debug | Objects client initialize lua scripts2
ping.0 | 5112 | 2021-12-10 20:34:52.876 | debug | Objects create User PubSub Client
ping.0 | 5112 | 2021-12-10 20:34:52.878 | debug | Objects client initialize lua scripts
ping.0 | 5112 | 2021-12-10 20:34:52.876 | debug | Objects create User PubSub Client
ping.0 | 5112 | 2021-12-10 20:34:52.874 | debug | Objects create System PubSub Client
ping.0 | 5112 | 2021-12-10 20:34:52.874 | debug | Objects create System PubSub Client
ping.0 | 5112 | 2021-12-10 20:34:52.871 | debug | Objects client ready ... initialize now
ping.0 | 5112 | 2021-12-10 20:34:52.871 | debug | Objects client ready ... initialize now
ping.0 | 5112 | 2021-12-10 20:34:52.834 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
ping.0 | 5112 | 2021-12-10 20:34:52.834 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

</body>
</html>`

Hast Du eine Idee, was ich noch versuchen könnte?

Danke im Voraus und Grüße

**Comment by buanet** [comment]
Hallo,
ich würde behaupten, dass der ioBroker user nicht die nötigen Rechte besitzt um ping auszuführen:

`STDERR: /bin/ping: socket: Operation not permitted `

Vielleicht kann Google da helfen. Kann den Fehler in meiner Testumgebung leider nicht reproduzieren. 

MfG,
André

**Comment by SmartHomer0** [comment]
>

**Comment by SmartHomer0** [comment]
Hallo André, Danke für Deine Antwort.
Als Feedback für Dich mein aktueller Stand:
Initiiert durch einen anderen Chat zu "ping-Problemen" im iobroker-Forum habe ich folgendes gemacht:
Docker-console: 
>pkill -u iobroker
>apt remove iputils-ping
>Docker-Container Stop
>Docker-Container Start
==> nun klappt es wieder mit dem Ping-Adapter

MfG

**Comment by buanet** [comment]
Hallo @SmartHomer0,
ist damit dein Problem behoben? Du hast den Issue geschlossen und wieder eröffnet. War das gewollt oder verklickt? 
Wenn alles ok ist, bitte schließen, andernfalls brauch ich nen kleinen Hint was ich noch tun kann. :)

MfG,
André
