### ISSUE TITLE
Update auf V6 - raspberry pi 4

### ISSUE THREAD

**Issue by Bodengriller** [buanet/ioBroker.docker#227]
Vermutlich liegt's an mir...ich komme aber nicht weiter.

Ich wollte das Update auf V6 auf meinem Raspberry 4 durchführen und bin dafür direkt den backup and restore weg gegangen.
-> Backup erzeugt -> container gestoppt -> alten iobroker-data ordner umbenannt, neuen Ordner erstellt, Backup hier reinkopiert -> mein docker-compose-file neu ausführen lassen.

Nun gibt es scheinbar Probleme (auch nach mehreren Stunden noch)
```
Starting ioBroker...,
 ,
Node.js[215]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.,
/opt/scripts/iobroker_startup.sh: line 505:   215 Aborted                 gosu iobroker node node_modules/iobroker.js-controller/controller.js,
tail: cannot read realtime clock: Operation not permitted,
```

scheint so als würde er keine Zeit-Daten bekommen?!

meine raspbian daten:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

auf dem Rasppi wurde update&upgrade ausgeführt und alles auf aktuellsten Stand gebracht.

hat jemand eine Idee, was hier faul ist?

Komplette Log inkl. einiger neustarts:
[iobroker_log.txt](https://github.com/buanet/ioBroker.docker/files/7745249/iobroker_log.txt)

zur Vollständigkeit: mein compose-file:
[docker-compose.yml.txt](https://github.com/buanet/ioBroker.docker/files/7745262/docker-compose.yml.txt)

**Comment by buanet** [comment]
Bitte mit der Fehlermeldung ´cannot read realtime clock: Operation not permitted` mal die Issues durchsuchen.
#199 #208 
Irgendwann solltest du dann hier ankommen: https://github.com/buanet/ioBroker.docker/issues/199#issuecomment-932918780

MfG,
André

**Comment by Bodengriller** [comment]
...peinlich... da hätte ich wohl besser suchen sollen - sorry

nun sieht's schon besser aus.
Vielen dank für deine Unterstützung und schöne Feiertage.

LG Markus
