### ISSUE TITLE
maintenance.sh upgrade --yes flag is ignored

### ISSUE THREAD

**Issue by thost96** [buanet/ioBroker.docker#228]
Hi,

the --yes flag on ./maintenance.sh upgrade is ignored, and the confirmation question is asked every time, which makes this option unusable. Also using -y returns the same error. Here is some output: 

```
root@iobroker:/opt/scripts# ./maintenance.sh upgrade --yes
You are now going to upgrade your js-controller.
As this will change data in /opt/iobroker, make sure you have a backup!
During the upgrade process the container will automatically switch into maintenance mode and stop ioBroker.
Depending of the restart policy, you container will be stoped/ restarted automatically after the upgrade.
Do you want to continue [yes/no]? 
```

iobroker.docker v6.0.0 
docker version 20.10.12, build e91ed57

**Comment by buanet** [comment]
Thank you, pr is merged. Will be available with new beta.

Regards,
André
