### ISSUE TITLE
Frage: redis extra-Container oder im ioBroker-Container

### ISSUE THREAD

**Issue by DerDoubleD** [buanet/ioBroker.docker#245]
Hallo 
Hab eine Verständnisfrage
wird redis durch das Startscript in den ioBroker-Container installiert oder muss ich einen eigenen Container mit redis aufsetzen?

Danke für die tolle Arbeit!!!

**Comment by buanet** [comment]
Hallo,
für Fragen gibt es die ioBroker Community und hier im Github den Bereich "Discussions". Bitte zukünftig dort fragen. 

Unter Docker bekommt jeder Service seinen eigenen Container, das gilt auch für Redis.
Das Startscript konfiguriert den ioBroker lediglich für den Zugriff auf eine Redis Instanz. Wo diese Instanz liegt ist dabei egal. Sie muss nur erreichbar sein.

MfG,
André
