### ISSUE TITLE
Allow skip reset folder permissions

### ISSUE THREAD

**Issue by viceice** [buanet/ioBroker.docker#251]
This should be skippable, as on restart of container it shouldn't required.

I would send a PR if a conditional reset would be accepted.

**Comment by buanet** [comment]
I've seen so many issues caused of wrong permissions that I simply added the check to every start of the container. 
There are a lot users copying the mounted directories for backup and restore without  taking care of permissions. Or even the host (NAS or whatever) does not care about when copying... So as long as I'm quite the only one supporting users when facing another permission issue this should be checked/ corrected on every start of the container.... it saves me a lot of time answering the same questions again and again. 
change my mind... :)

Regards,
André

**Comment by buanet** [comment]
@viceice It's two weeks now. As I got nothing from you I'll close this issue. If you want you can contact me directly or meet me at the ioBroker Discord Channel. I would appreciate that. 

Regards,
André

**Comment by viceice** [comment]
Sorry, very busy. I'll send a PR soon to optional skip resetting folder permission.
