### ISSUE TITLE
Not starting in host mode

### ISSUE THREAD

**Issue by viruz82** [buanet/ioBroker.docker#256]
Hi,

if I want to run iobroker in host mode I always get the following error:
`/opt/scripts/iobroker_startup.sh: line 201: [: !=: unary operator expected`

This is the line 201 in iobroker_startup.sh:
`if [ $(bash iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*') != $(hostname) ] && [ "$multihost" != "slave" ]
`

My docker is runing on a lxc container. Running other docker containers in host mode just works fine.
How can I fix it to get iobroker run in host mode? Thanks in advance.

Cheers
viruz

**Comment by buanet** [comment]
Hi,
I'm sorry. I can not reproduce your issue. Looks for me like a there is a problem getting the hostname from inside the container. Not sure if this has something to do with your docker+lxc setup. 
Are you able to retrieve the hostname with `hostname` command from inside the container? What's the output?

Would also be nice to see the whole log, not only the error message... 

Regards,
André

**Comment by buanet** [comment]
No more response.

**Comment by viruz82** [comment]
Hi @buanet ,

sorry for the late response.

Here's the log:

> --------------------------------------------------------------------------------
-------------------------     2022-05-13 08:11:31      -------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                 Welcome to your ioBroker-container!                  -----
-----                    Startupscript is now running.                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                        Debugging information                         -----
-----                                                                      -----
-----                                System                                -----
-----                    arch:                x86_64                       -----
-----                    hostname:            iobroker                     -----
-----                                                                      -----
-----                             Docker-Image                             -----
-----                    image:               v6.1.0                       -----
-----                    build:               2022-04-26T23:46:59+00:00    -----
-----                                                                      -----
-----                               Versions                               -----
-----                    node:                v14.19.1                     -----
-----                    npm:                 6.14.16                      -----
-----                                                                      -----
-----                                 ENV                                  -----
-----                    SETGID:              1000                         -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------

Updating Linux packages on first run...
dpkg-preconfigure: unable to re-open stdin:
(Reading database ... 32068 files and directories currently installed.)
Preparing to unpack .../gzip_1.10-4+deb11u1_amd64.deb ...
Unpacking gzip (1.10-4+deb11u1) over (1.10-4) ...
Setting up gzip (1.10-4+deb11u1) ...
(Reading database ... 32068 files and directories currently installed.)
Preparing to unpack .../liblzma5_5.2.5-2.1~deb11u1_amd64.deb ...
Unpacking liblzma5:amd64 (5.2.5-2.1~deb11u1) over (5.2.5-2) ...
Setting up liblzma5:amd64 (5.2.5-2.1~deb11u1) ...
(Reading database ... 32068 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_5.10.113-1_amd64.deb ...
Unpacking linux-libc-dev:amd64 (5.10.113-1) over (5.10.106-1) ...
Preparing to unpack .../nodejs_14.19.2-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.19.2-deb-1nodesource1) over (14.19.1-deb-1nodesource1) ...
Setting up linux-libc-dev:amd64 (5.10.113-1) ...
Setting up nodejs (14.19.2-deb-1nodesource1) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Done.

Registering maintenance script as command...
Done.

--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------

Existing installation of ioBroker detected in /opt/iobroker.

--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------

(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.

--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
/opt/scripts/iobroker_startup.sh: line 201: [: !=: unary operator expected
--------------------------------------------------------------------------------

Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).

--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------

Starting 

ioBroker... 

That's it, nothing else happens. 


And the hostname check:
root@iobroker:/opt/iobroker# hostname
iobroker

Cheers
Kai

**Comment by buanet** [comment]
What do you get with this command:

`iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*'`

According to your Log the Issue occurs within [this](https://github.com/buanet/ioBroker.docker/blob/3957414b2ba4ff362269b1b94a9c195b917471ac/debian/scripts/iobroker_startup.sh#L200) check. I'm not able to reprocduce it on my environments. I'm running iobroker in docker on lxc too, but use macvlan instead of host... What is your lxc based on? 

Regards,
André

**Comment by viruz82** [comment]
I don't get any feedback on this command.
But with this: iobroker object get system.adapter.admin.0
I get that:
` Could not connect to states database at 127.0.0.1:9000 (invalid protocol). Please make sure the configured IP and port points to a host running JS-Controller >= 2.0. and that the port is not occupied by other software!`

I don't get it. What has iobroker to do with port 9000? This is my portainer container. And when I change the Portainer port for example to 9001 the iobroker log says:
`Could not connect to states database at 127.0.0.1:9001 (invalid protocol). Please make sure the configured IP and port points to  by other software!`

edit:
When I stop portainer iobroker runs just fine:
`iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*'
iobroker`

What has this to do with portainer?

**Comment by Apollon77** [comment]
ioBroker uses Ports 9000 and 9001 nornmally for himself. SO if your portainer also uses this port this will give a conflict in host mode. Please move potainer to a different port or confiugure iobroker to use an other port

**Comment by viruz82** [comment]
Okay, thank you.
