### ISSUE TITLE
Fix description in documentation and Environment variables

### ISSUE THREAD

**Issue by Anzic23** [buanet/ioBroker.docker#262]
with the transition to the 4th version of the controller, it is possible to use JSONL as a base for objects and states. If you do not pay attention to this when updating the container, then you can get a non-working system, because. Environment variables can be "file", but should be "jsonl"
It would also be nice to specify in the possible Environment variables what can be selected as IOB_OBJECTSDB_TYPE jsonl (maybe even worth switching to it by default in new versions of the container)

**Comment by buanet** [comment]
> If you do not pay attention to this when updating the container, then you can get a non-working system, because. Environment variables can be "file", but should be "jsonl"

Yes, I see your issue. But to be honest, this seems to be a rare case. No more reports of it yet.
Best practice is to only set the ENVs you really need. Why did you set IOB_OBJECTSDB_TYPE to file in your container? There is no need to do so.
As long as you do not set a ENV, ioBroker will simply use the default values. If the default changes to foobar with the next js-controller update your iobroker will be fine...

> It would also be nice to specify in the possible Environment variables what can be selected as IOB_OBJECTSDB_TYPE jsonl (maybe even worth switching to it by default in new versions of the container)

I'm not sure what you want to tell me with that. There is nothing to switch in a new image version, as the container always uses the ioBroker default value as long as you do not overwrite it by ENV. If you have set an ENV it's in your responsibility to make sure the ENV is correct. There is no way for me to change the ENVs in your compose-file (or docker command) within an image update.

The documentation will be updated soon. 

Regards,
André

**Comment by Anzic23** [comment]
ah, that's it, Sorry, apparently I didn't read the documentation carefully enough, and didn't pay attention to the fact that inventories may not be required, moreover, it's better not to specify them if they are definitely not needed. And I thought that they must all be indicated, so I got into such a situation. Apparently this is why my iobroker.json is overwritten every time the container is restarted. Thanks for the clarification.
All the best!
Anzor :)
