### ISSUE TITLE
Possibility to adjust /etc/sudoers.d/iobroker file via ENV

### ISSUE THREAD

**Issue by M0dj0** [buanet/ioBroker.docker#266]
Hi @buanet,

in advance thank you for your great work for the iobroker docker container.
In my case I adjusted the /etc/sudoers.d/iobroker file to enable an iobroker script to talk to a wake on lan tool I installed separatly via the PACKAGES variable. Now every time I pull a new Image, of course I have to adjust the /etc/sudoers.d/iobroker manually again to grant the permissions. I would very much appreciate it if you implement an environment variable to adjust this file.

Thanks

**Comment by buanet** [comment]
Hi,
in this special case you better use the possibility to run individual [startup-scripts](https://docs.buanet.de/iobroker-docker-image/docs/#startup-scripts). This is build do "manipulate" the container as you want during first or every startup. 

regards,
André

**Comment by buanet** [comment]
No more response for 3 weeks now. Will close this. 

Regards,
André
