### ISSUE TITLE
iobroker_startup.sh unary operator expected

### ISSUE THREAD

**Issue by tobasium** [buanet/ioBroker.docker#271]
Hallo Zusammen,

ich bekomme den docker nicht auf meiner synology (DS1515+) zum laufen.

Egal ob ich Verzeichnis binde oder einfach nur den container starten will habe ich folgenden Fehler:

--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu... Done.
 
/opt/scripts/iobroker_startup.sh: line 212: [: !=: unary operator expected
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker...

Bin für jede Hilfe Dankbar.

**Comment by buanet** [comment]
Hi,
dein Log ist unvollständig. 
In den allermeisten Fällen ist diese Fehlermeldung nicht der Grund dafür dass ioBroker nicht läuft.
Leider schreibst du nix über dein Setup und was du überhaupt versucht hast. 

Hast du dich schon an die ioBroker Community (Forum/ Discord) gewandt? 

MfG,
André

**Comment by tobasium** [comment]
Ich hab glaub das Problem gefunden. iobroker läuft im host, portainer auch und da stört dann port 9000.

Dachte dadurch das ich redis nutze macht das nichts aber scheinbar doch.

Mit meinem alten Image hab ich die Probleme nicht. Da bin ich zu blind ran. 

Ich muss jetzt mal schauen was ich anpassen muss das es läuft ohne portainer zu ändern.

**Comment by tobasium** [comment]
Also ich hab jetzt Portainer auf einen anderen Port gesetzt. Anders bekomme ich es nicht zum Laufen. Mein Kopf will auch nicht mehr heute.

**Comment by buanet** [comment]
Hallo,
ich schließe diesen issue weil es offenbar am Portkonflikt lag. Die Fehlermeldung "unary operator expected" wird mit dem nächsten Update gefixt.

MfG,
André
