### ISSUE TITLE
mysqldump backitup schlägt fehl

### ISSUE THREAD

**Issue by 9Mad-Max5** [buanet/ioBroker.docker#273]
Hi,

Vielen Dank für den Container und die Arbeit die daran steckt.
Ich weiß, es gab schon ein ähnliches Issue hier, aber ich denke schon das es Sinn ergibt, die direkt in den Container einzubetten.

Bei mir hat:
apt install mariadb-client

geholfen, den leider stoppt der komplette Backupprozess, wenn er dieses Paket nicht findet.
Das ist natürlich leider nicht persistent deswegen wäre es schon ein Thema den Container dementsprechend anzupassen.

**Comment by Apollon77** [comment]
siehe Doku ... du kannst pakete angeben die beim container start automatisch installiert werden

**Comment by 9Mad-Max5** [comment]
Ok habs gefunden.
Bin noch bisher nicht auf das System eines Dockers gestoßen, welches standardmäßig das Nachinstallieren von paketen zulässt.
Sicherlich wäre es eine gute Sache etwa in der README einen vermerk auf die Problematik mit backitup zu machen.
Ansonsten sind mir noch keine Adapter aufgefallen, die auf den ersten Blick klappen, es aber doch nicht tun.
Dass er nicht funktioniert ist, mir auch nur just aufgefallen als ich überprüft habe, ob ich ein aktuelles habe, da der Adapter ja meist im Hintergrund von alleine arbeitet und auch in meinem Fall nicht auf Gelb geht.

**Comment by buanet** [comment]
Moin, 
zum Einen liegt @Apollon77 natürlich richtig. Wenn Pakete fehlen kannst du diese über die Umgebungsvariable PACKAGES automatisch nachinstallieren lassen (siehe Doku).
Zum Anderen sollten dir die Optionen für das backup externer Datenbanken unter Docker gar nicht angeboten werden!?
 
![image](https://user-images.githubusercontent.com/16137672/180966691-d133c340-9840-405f-a9ac-a18a5b0795d7.png)

@simatec:  Wurde da was geändert?

**Comment by simatec** [comment]
Nein da wurde nix geändert. 
externe Datenbanken werden in Backitup für Docker nicht unterstützt und sind nicht wählbar. 
Grundlage der Abfrage ist der file im Image zur Docker Erkennung

**Comment by Apollon77** [comment]
Vllt ein backup eingespielt von ner "nicht docker" version? ;-)

**Comment by simatec** [comment]
Das sollte egal sein, da das Docker Image vom Andre die Erkennung integriert hat
Backitup prüft das beim öffnen der Config und stellt nur die Backupmöglichkeiten zur Verfügung, die zulässig sind

**Comment by buanet** [comment]
Möglich dass das verwendete Docker Image die Erkennung noch nicht drin hat. :)

@simatec Ich plane aktuell das Backup der externen DBs unter Docker aktivierbar zu machen (aber nicht von Hause aus mit zu liefern). Gibt dann in der Doku für die einzelnen Datenbanken die Möglichkeit die Voraussetzungen zu schaffen (Kurzanleitung mit Hinweisen). Wir müssten dann nur mal schauen wie wir das dann im Backitup abfangen. Entweder wir lassen generell zu, dass die Optionen gewählt werden (mit ner Hinweis Bubble zur Doku) oder wir prüfen in irgendeiner Form und schalten dann das Häkchen frei. Ich schlage vor das besprechen wir wenn ich die Doku soweit vorbereitet habe...

**Comment by simatec** [comment]
Lass uns das mal in Ruhe besprechen. 
Schaue das ich die nächsten Wochen dafür dann irgendwie mal meinen Kopf freibekomme.
