### ISSUE TITLE
v7.0.1: After restore VIS cannot be installed / get going

### ISSUE THREAD

**Issue by RkcCorian** [buanet/ioBroker.docker#276]
Environment: Docker at Synology NAS

Procedure: I have v6.0.0 running since months and realized that there is a new v7.0.1. I created a backup (Backitup) and restored by putting the backup in the new iobroker folder and created a new container as usual. When it comes to the installation of adapters it fails for the VIS. This was not a problem with v6.0.0.

In sum the following I did  to workaround it. It has to be done AFTER restored everything AND BEFORE restarting for the adapter installation:
_Not specific for this version/problem but also anoying_
a.	„pkill -u iobroker“ executed
b.	„iobroker host this“ executed
_Specifically for this problem_
i.	„cd /opt/iobroker“ executed (only in case not already in the folder)
ii.	„npm i iobroker.vis@1.4.15” (choose your version) executed
iii.	„iobroker upload vis“ executed

I hope this will be fixed (or workaround will be in place) for future versions...

Compare also similar problem descriptions...
- https://forum.iobroker.net/topic/54999/gel%C3%B6st-vis-nach-backup-restore-nicht-mehr-aktiv
- https://forum.iobroker.net/topic/29707/vis-nicht-erreichbar/14
- https://forum.iobroker.net/topic/54999/gel%C3%B6st-vis-nach-backup-restore-nicht-mehr-aktiv

**Comment by RkcCorian** [comment]
@buanet : Btw. vielen Dank für Deine Arbeit und die Bereitstellung des Containers!!!

**Comment by Glasfaser-io** [comment]
Das ist aber kein Fehler vom Image v7.0.1 .

Wie du auch selber verlinkt hast , sind dort Raspberry installationen ,
bzw. auch Proxmox / verschiedene Umgebungen usw. vorhanden .

Aber hier bist du schon richtig gewesen , unter :
https://github.com/ioBroker/ioBroker.vis/issues/440
aber der ist **Closed** , du kannst gerne bei VIS ein neues Issues eröffnen .

**Comment by RkcCorian** [comment]
@Glasfaser-io : Hmm... ich hab mal das issue von VIS kommentiert. Aus meiner Sicht muss dieses entweder wieder geöffnet werden oder tatsächlich ein neues zum gleiche Thema erstellt werden. Mal schauen welche Rückmeldung ich bekomme...

**Comment by buanet** [comment]
Hallo,
ohne mich in den Vis Fehler jetzt ein zu lesen: Fehler vom Docker Image oder ioBroker Fehler?

Wenn ich den vorletzten Kommentar von https://github.com/ioBroker/ioBroker.vis/issues/440 richtig deute, dann tritt das nicht Docker spezifisch auf. Demzufolge würde ich den Issue hier schließen wollen. 

MfG,
André

**Comment by RkcCorian** [comment]
@buanet : Ja, vermute auch, dass es nicht vom Container selber kommt. Es scheint an der VIS zu liegen. Bislang äußert sich aber keiner dazu, was schade ist.

**Comment by RkcCorian** [comment]
Closed as seems to be an issue of VIS and not of the container.
