### ISSUE TITLE
ioBroker container does not start after update to v7.1.0

### ISSUE THREAD

**Issue by Curtis777** [buanet/ioBroker.docker#289]
Since updating the cointainer iobroker will not start again. Stopped after setting guid stuff. Reinstall of container doesnt help

**Comment by Apollon77** [comment]
is there any chance to see logs or other information that could help to better see your issue?

**Comment by buanet** [comment]
Please provide the full log of your container start.

**Comment by evilmon** [comment]
same error here. You find the startup-log attached.
[iobroker startup.txt](https://github.com/buanet/ioBroker.docker/files/9907311/iobroker.startup.txt)

**Comment by buanet** [comment]
@evilmon Unraid? I'm wondering about this log lines before the log starts:

```
text  error  warn  system  array  login  

dpkg-preconfigure: unable to re-open stdin: 
groupmod: GID '100' already exists
```

Any idea?

**Comment by evilmon** [comment]
yes running on unraid. no idea what it means...

**Comment by KhaosRipper** [comment]
gleiches Problem auch bei mir. (Unraid)

[iobroker.startup.txt](https://github.com/buanet/ioBroker.docker/files/9907592/iobroker.startup.txt)

**Comment by buanet** [comment]
Seems as only Unraid is affected. Please stay on v7.0.1 until I figured out what's wrong with Unraid...

**Comment by vepman** [comment]
Bei mir auch  unter Docker auf Synology DS218+:
[iobroker.startup.txt](https://github.com/buanet/ioBroker.docker/files/9907949/iobroker.startup.txt)

**Comment by tigger30926** [comment]
> Seems as only Unraid is affected. Please stay on v7.0.1 until I figured out what's wrong with Unraid...


Thank you very much, I have the same problem right now. Is there any way to go back to version 7.0.1?

**Comment by buanet** [comment]
ok, it's not Unraid related, but affects mostly Unraid users because of the use of gid 100 as default parameter in iobroker container template... Not sure why this was made in the template, but might have any unraid specific reason...

However, I could determine the root cause and already created a fix for that. The build is running, new patch version v7.1.1 will be available soon. 

Hopefully this will fix it. :)

Regards,
André

**Comment by buanet** [comment]
@vepman 

> Bei mir auch unter Docker auf Synology DS218+:

Gibt es einen Grund warum du GID 100 und UID 99 benutzt?

**Comment by buanet** [comment]
@tigger30926 

> Thank you very much, I have the same problem right now. Is there any way to go back to version 7.0.1?

Simply use the v7.0.1 tag when creating your container.

**Comment by tigger30926** [comment]
> @tigger30926
> 
> > Thank you very much, I have the same problem right now. Is there any way to go back to version 7.0.1?
> 
> Simply use the v7.0.1 tag when creating your container.

Ok, thank you very much. Sorry, I'm still a total beginner, so where exactly do I have to do something in Unraid to get V7.0.1 installed again?

**Comment by vepman** [comment]
> @vepman
> 
> > Bei mir auch unter Docker auf Synology DS218+:
> 
> Gibt es einen Grund warum du GID 100 und UID 99 benutzt?

Hab ich nicht. Beide sind auf 1000:

-----                    SETGID:              1000                         -----

-----                    SETUID:              1000

**Comment by tigger30926** [comment]
For all those who also currently have the problem in Unraid. 
Please change the following in your iobrocker settings in Unraid from **buanet/iobroker** to **buanet/iobroker:v7.0.1**

After that, everything should work again for the time being. 

Thanks not to me but to "igel81" and "buanet"
[Unraid-Forum](https://forums.unraid.net/topic/101016-support-buanet-iobroker/?do=findComment&comment=1186397)

**Comment by buanet** [comment]
@vepman 

???
Wenn ich das Logfile aus deinem Post herunter lade, dann steht da aber was anderes...

**Comment by buanet** [comment]
Update: Build ist durch, v7.1.1 steht zum Download bereit. Bitte mal testen. Ich konnte den Fehler im Testsystem damit nicht mehr reproduzieren. 

MfG,
André

**Comment by tigger30926** [comment]
> Update: Build ist durch, v7.1.1 steht zum Download bereit. Bitte mal testen. Ich konnte den Fehler im Testsystem damit nicht mehr reproduzieren.
> 
> MfG, André

Perfekt, jetzt läuft es bei mir auch wieder mir der Version 7.1.1.  Vielen Dank für die schnelle Hilfe.

**Comment by vepman** [comment]
Sorry, falsche Log-File hochgeladen.


[log.txt](https://github.com/buanet/ioBroker.docker/files/9908695/log.txt)

**Comment by buanet** [comment]
@vepman Du hast ein anderes Problem:

`Setting permissions for /dev/ttyACM1... chown: cannot access '/dev/ttyACM1': No such file or directory`

Deine Config stimmt nicht. Gibt es das Device? Ist es korrekt durchgereicht?
Die neue Version des Docker Containers geht restriktiver mit Fehlern in der Konfiguration um. Prüfe mal deine Systemvariable

`USBDEVICES:          /dev/ttyACM0;/dev/ttyACM1 `

MfG,
André

**Comment by vepman** [comment]
@buanet
Ja, ist ein Zigbee-Stick. Den muss ich leider nach Updates immer wieder manuell einbinden.
Das liegt aber daran, dass Synology seit DSM 7 irgendwelche Restriktionen gemacht hat.
Das kriege ich schon hin.
Aber Version 7.11 von dir sofort gut gestartet.

**Comment by Shadow27374** [comment]
Hallo, ich habe auch dieses Problem mit der Endlosschleife.

Ich habe folgende Tags probiert:
buanet/iobroker::latest
buanet/iobroker::latest-v7
buanet/iobroker:v7.1.1
buanet/iobroker:v7.0.1-amd64

Nur buanet/iobroker:v7.0.1-amd64 funktioniert.

Welche Logs werden benötigt und wie komme ich daran? Der Docker Container startet ja leider immer neu.

**Comment by buanet** [comment]
Moin,
liegt vielleicht daran, dass sich hinter den ersten drei Tags dasselbe Image versteckt. :)
Wenn v7.1.1 bei dir nicht funktioniert benötige ich dein Logfile vom Container Start um zu sehen was da schief läuft. Allerdings kann ich dir nicht sagen wie du da dran kommst weil ich nicht weiß welches System bzw. welche Oberfläche du für Docker benutzt. Kommandozeile? Portainer? Synology DSM? Unraid?  
In der Regel gibt es in jeder Oberfläche beim entsprechenden Container einen Menüpunkt Logs oder Protokolle.  Für die Kommandozeile gibt es den Befehl `docker logs`. Mehr dazu findest du in der Docker Doku.

MfG,
André

**Comment by Shadow27374** [comment]
Hier läuft ein Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64) sowohl mit Zugriff auf die Konsole als auch Portainer.

Portainer spuckt mir folgendes aus: 
[_iobroker_logs.txt](https://github.com/buanet/ioBroker.docker/files/9921792/_iobroker_logs.txt)

**Comment by buanet** [comment]
@Shadow27374 Du hast ein anderes Problem. Wir machen hier weiter #293 

MfG,
André
