### ISSUE TITLE
ioBroker startet nicht nach update auf v7.1.1

### ISSUE THREAD

**Issue by buanet** [buanet/ioBroker.docker#293]
Hier läuft ein Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64) sowohl mit Zugriff auf die Konsole als auch Portainer.

Portainer spuckt mir folgendes aus: 
[_iobroker_logs.txt](https://github.com/buanet/ioBroker.docker/files/9921792/_iobroker_logs.txt)

_Originally posted by @Shadow27374 in https://github.com/buanet/ioBroker.docker/issues/289#issuecomment-1300675099_

**Comment by buanet** [comment]
@Shadow27374

In deinem Log sehe ich, dass der Container Probleme beim Setzen des Hostnamens hat. Offenbar wird dein admin.0 nicht gefunden... 

```
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
The object system.adapter.admin.0 was not found!
Hostname in ioBroker does not match the hostname of this container.
The object system.adapter.admin.0 was not found!
iobroker host <hostname>
Set host to given hostname
      
:
  iobroker host this               Initialize current host
  iobroker host set <hostname>     Set host with specified hostname
  iobroker host remove <hostname>  Remove host with specified hostname
Options:
  --help  Show help  [boolean]
Not enough non-option arguments: got 0, need at least 1
Updating hostname to iobroker...        
```

du bist doch jetzt wieder auf v7.0.1, richtig? Kannst du mal im ioBroker schauen welche nummer deine Admin instanz hat? 

![image](https://user-images.githubusercontent.com/16137672/199600218-263a424b-495f-4a5d-85e4-956cc577131b.png)


MfG,
André

**Comment by Shadow27374** [comment]
Das ist richtig, da hatte ich mal vor über einem Jahr irgendwas kaputt gemacht und dann hatte ich admin.1.
Das funktionierte damit auch wunderbar bis vor ein paar Tagen.

**Comment by Shadow27374** [comment]
So nun habe ich wieder admin.0 und damit geht es. Er will also zwingend die aller erste Instanz haben.

**Comment by buanet** [comment]
Ja, ich bin davon ausgegangen, dass es immer eine admin.0 instanz gibt. Ich schaue mal ob ich das irgendwie sinnvoll abfangen kann.... Schön dass es jetzt geht. :)

MfG,
André

**Comment by Shadow27374** [comment]
Ja bei mir geht es, Danke hierfür!

**Comment by Apollon77** [comment]
> Ja, ich bin davon ausgegangen, dass es immer eine admin.0 instanz gibt

hehe ... Nee nicht sichergestellt. vllt "iob list instances" und da admin greppen und die erste instanz nehmen?

**Comment by buanet** [comment]
Ja, so in etwa würde ich das machen. :)

**Comment by buanet** [comment]
This should be fixed with patch [v7.1.2](https://github.com/buanet/ioBroker.docker/releases/tag/v7.1.2).
