### ISSUE TITLE
ioBroker container run by podman: add some documentation

### ISSUE THREAD

**Issue by stuehmer** [buanet/ioBroker.docker#294]
I am looking for fellow users of Podman to share some experiences and possibly add these to the documentation.
I tried adapting the command line `docker run [...] docker.io/buanet/iobroker:latest-v7` to `podman run [...] docker.io/buanet/iobroker:latest-v7` However during startup I get several occurrences of `Operation not permitted`.

After diagnosing the problem using https://www.redhat.com/sysadmin/container-permission-denied-errors I narrowed it down to a missing [Linux capability](https://man7.org/linux/man-pages/man7/capabilities.7.html) `NET_RAW` which Docker usually allows but with Podman must be enabled specifically. So I ended up at `podman run --name iobroker --cap-add net_raw [...] docker.io/buanet/iobroker:latest-v7`

Bringing it all together, also using a macvlan network (because I wanted a dedicated DHCP IP address for the container) I ended up at a rootful podman container as follows:
```
sudo podman run \
  --name iobroker \
  --cap-add net_raw \
  --tty \
  --net macvlan \
  --mac-address=<AA:BB:CC:... a MAC for which I have a DHCP reservation on my LAN> \
  -e SETUID=<UID on host e.g. 998> \
  -e SETGID=<GID on host e.g. 998> \
  --volume iobroker_data_v7:/opt/iobroker:rw,exec \
  --hostname iobroker \
  --label "io.containers.autoupdate=image" \
  docker.io/buanet/iobroker:latest-v7
```
Any other Podman experience out there?

**Comment by buanet** [comment]
Hi,
at the moment there is no support for running a ioBroker container in podman. 

Please do not use the issues for questions or support. Use the discussions instead. 
Or better: Join the ioBroker community forum, Discord channel or Facebook group and place your questions there. 

As I see no issue here, I will close this now. 
Thank you.

Regards,
André
