### ISSUE TITLE
[Problem]: USB Stick conbee II

### ISSUE THREAD

**Issue by Mephisto090** [buanet/ioBroker.docker#302]
### Description

Hallo, 

ich versuche wie in deinem Tutorial (https://smarthome.buanet.de/2020/02/usb-devices-im-iobroker-docker-container-nutzen/) den Conbee II ins Docker zu bekommen. Leider wird mir bei "dmesg" nichts sinvolles ausgeben und "lsusb" funktioniert nicht. Ich habe es auch im Privileged Mode (On) versucht bzw. pauschal irgendwelche Devices hinzugefügt. (/dev/ttyUSB0)

Leider funktioniert auch nicht: "ls -al /dev/serial/by-id/"

Zur ENV List habe ich auch "USBDEVICES" mit einer leeren Value hinzugefügt.

Der USB-Stick funktioniert auch Problemlos unter deCONZ Windows.

### Image version

latest

### Docker logs

![image](https://user-images.githubusercontent.com/85995176/204149953-d0a634e4-900d-4018-b25d-0b683d1ba13b.png)
![image](https://user-images.githubusercontent.com/85995176/204149985-fb1ad9ae-453d-497b-a12f-8d85246d466c.png)

**Comment by Mephisto090** [comment]
Es handelt sich um docker-windows und eine Windowsmaschine

https://learn.microsoft.com/de-de/windows/wsl/connect-usb?source=recommendations

**Comment by buanet** [comment]
Moin,
für support Fragen wende dich bitte an die iobroker community über discord, Facebook, Telegram oder das iobroker Forum.
Darüber hinaus unterstützen wir derzeit kein Docker unter Windows. Das verlinkte Tutorial bezieht sich auf Docker unter Linux. Ich bin mir ziemlich sicher, dass das auf Docker unter Windows nicht passt...

MfG,
André

**Comment by Mephisto090** [comment]
https://github.com/dorssel/usbipd-win/wiki/WSL-support

Du müsstest nur das hier hinzufügen:

sudo apt install linux-tools-virtual hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip `ls /usr/lib/linux-tools/*/usbip | tail -n1` 20

dann müsste es theoretisch gehen. :)

**Comment by buanet** [comment]
Docker unter Windows user? Bitte hier melden: #303
