### ISSUE TITLE
[Problem]: After adding USBDEVICES iobroker did not start ( restart in a loop )

### ISSUE THREAD

**Issue by GTV1** [buanet/ioBroker.docker#307]
### Description

First sorry for my bad english. I have the image running on a Synology with DSM 7.1 in Docker. I'm trying to get a Sonoff zigbee stick to work. The stick will be recognized by the Synology system. To integrate the stick in Docker, I entered /dev/ttyACM0 under USDBEVICES. Now when I restart the container, the container restarts every few seconds in a loop. What am I doing wrong ? 

Habe gerade gesehen das ich auch in deutsch hätte schreiben können #62 
Problem: Ich versuche seit ein paar Wochen einen Sonoff USB Zigbee Stick zum laufn zu bekommen. Wenn ich unter USDBEVICES  /dev/ttyACM0 eintrage un den Docker neu starte restartet sich der Docker in einer Schleife. Wirklich was shen im Protokoll kann man leider nicht da der star schon sehr früh abbricht. (zumindest sehe ich da nichts ;-) ) 

### Image version

v7.1.2

### Docker logs

```shell
Sorry no log available where you could see what is happening.
```

**Comment by buanet** [comment]
Sorry, aber das ist kein Fehler vom Image!
So wie du deine Konfiguration schilderst ist sie einfach unvollständig.
Hättest du das Container Log gelesen und gepostet, wäre dir ein Link zur Doku aufgefallen.
Da steht wahrscheinlich sowas im Log: 

```
USBDEVICES is set.
Looks like the device "/dev/ttyACM0" does not exist.
Did you mount it correctly by using the "--device" option?
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/#mounting-usb-devices).
```

 Wenn du dann den Link öffnest findest du dies: 
***
### Mounting USB devices

If you want to use a USB device within ioBroker inside your container don´t forget to [mount the device](https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device) on container startup and use the ENV "USBDEVICES" to give ioBroker access to it.
***

Ich weiß ehrlich gesagt nicht wie ich es noch besser dokumentieren soll.... Es reicht eben nicht, nur die Umgebungsvariable "USBDEVICES" anzugeben. 

Für Supportanfragen wende dich bitte an die ioBroker Community (Forum, Discord, Telegram, Facebook) oder nutze die [Discussions](https://github.com/buanet/ioBroker.docker/discussions). 

Danke.
