### ISSUE TITLE
Infinite Bootloop: Cannot find module iobroker.js-controller/iobroker.js

### ISSUE THREAD

**Issue by mschewie5** [buanet/ioBroker.docker#308]
Hi,
ich bekomme seit grade das Docker Image nicht mehr zum starten. Ich hatte zufällig gesehen das eine neue Version verfügbar war und direkt ein pull gemacht, dann compose up und nach einiger ins Log geschaut. Dort bricht das Script immer wieder ab, im Step 3, Fehlermeldung:  
(Re)setting permissions (This might take a while! Please be patient!)... Done.
Fixing "sudo-bug" by replacing sudo with gosu... Done.

node:internal/modules/cjs/loader:998
  throw error;
^
Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
  code: 'MODULE_NOT_FOUND',
}

There was a problem detecting the admin instance of your iobroker.
Make sure the ioBroker installation you use has an admin instance or start over with a fresh installation and restore your configuration.

Docker läuft in der aktuellsten Version auf einem aktualisierten RaspberryPi 4 (aarch64). Image Version 7.2.0. Ich habe auch die letzte Version 7.1.2 probiert, selber Fehler.
Ich hoffe die Informationen helfen weiter.

**Comment by Apollon77** [comment]
This error means that the js-controler is not correctly installed ...

**Comment by buanet** [comment]
@mschewie5 Ist das Thema noch aktuell?

**Comment by buanet** [comment]
As there is no more activity here, I'll close this. 

Regards,
André
