### ISSUE TITLE
[Problem]: Update to js-controller 4.0.24

### ISSUE THREAD

**Issue by etofi** [buanet/ioBroker.docker#313]
### Description

Please make a new docker build with js-controller 4.0.24

### Image version

7.2.0

### Docker logs

```shell
No logs.
```

**Comment by buanet** [comment]
There are two issues on this. 
The first is already solved by @Apollon77. There was an issue with npm, so v4.0.24 was not installed as latest stable during ioBroker setup. 
The second one deals with gh actions. I successfully tested some changes to the build process of the images dev tag. But I still have to adapt these to the other build processes for beta and latest image tags. So this may take some more time. I will close this issue once the build is fixed and the a new image is available... 

Regards,
André

**Comment by buanet** [comment]
**Workaround**
Manually update js-controller after setting up your container using the maintenance script: 

`maint upgrade`

Regards,
André

**Comment by buanet** [comment]
Build is fixed. Iobroker image is up to date. 

Regards,
André
