### ISSUE TITLE
[Problem]:  Restart Loop Startup Skript

### ISSUE THREAD

**Issue by RdTrxx** [buanet/ioBroker.docker#319]
### Description

Moin,

ich habe einen neuen Container aufgesetzt mit neuem Daten-Volume. Nach dem Start bzw. durchlaufen des Startup Skript startet der Container neu und das Startup Skript beginnt wieder von vorne. Usw.

Wie kann ich den Fehler finden?

Gruß
Volker

Raspberry Pi 3B+
Aufgesetzt in Portainer.io als Stack (docker-compose) mit diesem Skript:

version: '3'

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker:latest-v7
    hostname: tecsrv
    network_mode: bridge
    restart: always
    ports:
      - "8081:8081"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - iobrokerdata:/opt/iobroker
    environment:
      USBDEVICES: "/dev/ttyACM0;/dev/ttyACM1"
      IOB_MULTIHOST: "Slave"
      IOB_OBJECTSDB_HOST: "192.168.27.203"
      IOB_OBJECTSDB_PORT: "9001"
      IOB_OBJECTSDB_TYPE: "jsonl"
      IOB_STATESDB_HOST: "192.168.27.203"
      IOB_STATESDB_PORT: "9000"
      IOB_STATESDB_TYPE: "jsonl"
   
volumes:
    iobrokerdata:

### Image version

V7.2.0

### Docker logs

```shell
--------------------------------------------------------------------------------
-------------------------     2023-02-12 11:19:41      -------------------------
--------------------------------------------------------------------------------
-----                                                                      -----
----- ██╗  ██████╗  ██████╗  ██████╗   ██████╗  ██╗  ██╗ ███████╗ ██████╗  -----
----- ██║ ██╔═══██╗ ██╔══██╗ ██╔══██╗ ██╔═══██╗ ██║ ██╔╝ ██╔════╝ ██╔══██╗ -----
----- ██║ ██║   ██║ ██████╔╝ ██████╔╝ ██║   ██║ █████╔╝  █████╗   ██████╔╝ -----
----- ██║ ██║   ██║ ██╔══██╗ ██╔══██╗ ██║   ██║ ██╔═██╗  ██╔══╝   ██╔══██╗ -----
----- ██║ ╚██████╔╝ ██████╔╝ ██║  ██║ ╚██████╔╝ ██║  ██╗ ███████╗ ██║  ██║ -----
----- ╚═╝  ╚═════╝  ╚═════╝  ╚═╝  ╚═╝  ╚═════╝  ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝ -----
-----                                                                      -----
-----              Welcome to your ioBroker Docker container!              -----
-----                    Startupscript is now running!                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                          System Information                          -----
-----                    arch:                armv7l                       -----
-----                    hostname:            tecsrv                       -----
-----                                                                      -----
-----                          Version Information                         -----
-----                    image:               v7.2.0                       -----
-----                    build:               2023-02-10T23:45:25+00:00    -----
-----                    node:                v16.19.0                     -----
-----                    npm:                 8.19.3                       -----
-----                                                                      -----
-----                        Environment Variables                         -----
-----                    IOB_MULTIHOST:       Slave                        -----
-----                    IOB_OBJECTSDB_HOST:  192.168.27.203               -----
-----                    IOB_OBJECTSDB_PORT:  9001                         -----
-----                    IOB_OBJECTSDB_TYPE:  jsonl                        -----
-----                    IOB_STATESDB_HOST:   192.168.27.203               -----
-----                    IOB_STATESDB_PORT:   9000                         -----
-----                    IOB_STATESDB_TYPE:   jsonl                        -----
-----                    SETGID:              1000                         -----
-----                    SETUID:              1000                         -----
-----                    USBDEVICES:          /dev/ttyACM0;/dev/ttyACM1    -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------
 
Updating Linux packages on first run... 
Done.
 
Registering maintenance script as command... Done.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in "/opt/iobroker".
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
Hostname in ioBroker matches the hostname of this container.
No action required.
 
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
USBDEVICES is set.
Looks like the device "/dev/ttyACM0" does not exist.
Did you mount it correctly by using the "--device" option?
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/#mounting-usb-devices).
 
This Script will exit now.
```

**Comment by buanet** [comment]
Hallo,
hast du mal versucht das Log zu lesen? Ich dachte ich habe eine aussagekräftige Logausgabe eingebaut...

```
USBDEVICES is set.
Looks like the device "/dev/ttyACM0" does not exist.
Did you mount it correctly by using the "--device" option?
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/#mounting-usb-devices).
```

Kurzum, deine Konfiguration ist falsch. Du hast zwar die Umgebungsvariable "USBDEVICES" gesetzt, aber die Devices nicht in den Container durchgereicht, oder `Did you mount it correctly by using the "--device" option?`
Falls du Unterstützung bei Aufsetzen benötigst, wende dich am besten an die ioBroker Community (Forum, Discorsd, Telegram, Facebook). Ich sehe hier keinen Issue, daher schließe ich das hier. 

MfG,
André

**Comment by RdTrxx** [comment]
Hallo,

das war mir klar. Ich habe noch keine USB-Devices zum durchreichen da ich das System erst am Schreibtisch vorbereite und die Geräte später anschließe. Deswegen habe ich keine /dev durchgereicht weil sonst der Container nicht starten kann.

Mir war nicht klar das das Startup Skript das von 

"Looks like the device "/dev/ttyACM0" does not exist."
"Did you mount it correctly by using the "--device" option?"

im LOG spricht es als schwerwiegenden Fehler auslegt und sich selbst deswegen neu startet.
Da hätte ich erwartet das das auch so ausgegeben wird "Restart des Skripts ...", "Fataler Fehler ..." und nicht als "Looks like ..."

Trotzdem Danke für die Antwort und die super Arbeit!

Gruß
Volker

**Comment by buanet** [comment]
Wie man es macht ist es sowieso falsch...
ich dachte halt dass die Info mit dem Hinweis auf Fehlkonfiguration und in der Folge ein `This Script will exit now.` ausreichen um zu verdeutlichen das was nicht stimmt. Es ist ja an sich kein "Fataler Fehler", aber halt eine Konfiguration die das Script nicht toleriert. 
Grundsätzlich ist es so, dass das Startscript ioBroker nur startet, wenn die Konfiguration vollständig und funktional ist. Andernfalls wird immer mit entsprechender Meldung abgebrochen. 
Der Restart Loop resultiert dabei im Übrigen nicht aus dem Script selbst, sondern aus deiner Restart Policy `restart: always`... Andernfalls würde der Container nach dem Fehler beendet. 

MfG,
André
