### ISSUE TITLE
Maybe mistyped ture instead of true

### ISSUE THREAD

**Issue by Tschak77** [buanet/ioBroker.docker#322]
# Prepare and install ioBroker
RUN mkdir -p /opt/scripts/.docker_config/ \
    && echo "starting" > /opt/scripts/.docker_config/.healthcheck \
    && echo "${VERSION}" > /opt/scripts/.docker_config/.thisisdocker \
    && echo "ture" > /opt/.first_run \
    # Run installer
    && curl -sL https://iobroker.net/install.sh | bash - \
    # Deleting UUID from build
    && iobroker unsetup -y \
    && echo "ture" > /opt/iobroker/.fresh_install \

**Comment by buanet** [comment]
Yes thank you. I wanted this to be "true". :) I've changed it. 

As this parameter is only written to have no empty files, the typo has no impact to the image and it's function.
The startup script only checks if the file exists, not what parameter is written to it. So no worry about something that is not working. :)

Thanks for the hint. 

Regards,
André
