### ISSUE TITLE
[Feature Request]: Docker image verkleinern 

### ISSUE THREAD

**Issue by HReimann** [buanet/ioBroker.docker#323]
### Description

Hallo,
Danke für deine hervorragende Arbeit! 

Bei dem Docker Build Prozeß wird pro RUN Befehl leider ein neuer Layer im Image angelegt,
Dadurch enthält das Image auch Artefakte, welche mit dem 2. RUN erst aufgeräumt werden.
Hier empfiehlt es sich am Ende der jeweiligen  RUN die entsprechenden Artefakte zu beseitigen oder mit nur einem RUN zu arbeiten. 
Die Einsparung liegen bei dem getesteten Image bei ca. 300MB.

P.S. Mit dem Befehl "dive" kann nab das Image analysieren.

**Comment by buanet** [comment]
Hi, danke für den Tip mit dive.  Habe das Dockerfile jetzt ein bisschen optimiert. Kommt mit dem nächsten Release.
Auf 300 MB Einsparung bin ich allerdings nicht gekommen. Aber immerhin 200 MB :)

Vorher (beta image):
![image](https://user-images.githubusercontent.com/16137672/223645578-82613637-bea3-4d75-8f13-4441bf6dae1b.png)

 Nachher: 
![image](https://user-images.githubusercontent.com/16137672/223645949-b348462e-7feb-49c1-b303-1fafdd2ee1ec.png)

MfG,
André
