### ISSUE TITLE
[Problem]: Images newer than v7.1.2 are broken on ghcr.io - Docker hub is working!

### ISSUE THREAD

**Issue by viceice** [buanet/ioBroker.docker#330]
### Description

```console
> docker pull ghcr.io/buanet/iobroker:v8.0.0
3e5c3c6b6ad8: Download complete
8c40556c286d: Downloading [>                                                  ]       0B/1.241kB
failed to copy: httpReadSeeker: failed open: content at https://ghcr.io/v2/buanet/iobroker/manifests/sha256:8c40556c286df01c87a37565e1cee62399b088b7a26766799c53f5ad60cb76b1 not found: not found
```

### Image version

v8.0.0

### Docker logs

```shell
No logs, docker pull not possible
```

**Comment by viceice** [comment]
docker hub is working
```console
> docker pull iobroker/iobroker:v8.0.0
4f01f71c55c1: Download complete
8f07a34e493c: Download complete
bc6f7a4756d0: Download complete
4f4fb700ef54: Exists
afd54f259fc0: Download complete
3f9582a2cbe7: Download complete
1c1c07a9c0ac: Download complete
25b2c127f6ab: Download complete
docker.io/iobroker/iobroker:v8.0.0
```

**Comment by buanet** [comment]
Possibly related to https://github.com/docker/build-push-action/issues/851

**Comment by viceice** [comment]
maybe disable provenance for now for GitHub? so the builds are working again?

**Comment by buanet** [comment]
Build is still not working with ghcr.io. But it's working fine with Docker Hub. So the workaround is pulling the image from there.

Seems the image is pushed successfully, but there is some issue with the image manifest.
It's more or less a bug of buildx or build-and-push action. I have no more ideas and not enough time to work into this at the moment. Have subscribed some related issues. Will come back to this when there are some news coming up.
Any help appreciated.

**Comment by buanet** [comment]
I recently changed the title of this issue for documentation purpose. 

Investigation result: Looks like the manifest generated for multiarch images by "build and push" action (with buildx) is not supported by Github container repo (ghcr.io). As I don't want to change the build process to build the images in separate steps (takes a lot longer!) this will remain broken until build and push and/or buildx fixes this. 

@viceice provenance is now disabled, but did not fix this. 

WORKAROUND: Pull Image from Docker Hub.

Regards,
André

**Comment by viceice** [comment]
that's strange, i use buildx for multi arch too and those works fine on ghcr.
so it must be something with the action.
🤔

https://github.com/containerbase/base

**Comment by buanet** [comment]
Tell me what's wrong. :)
https://github.com/buanet/ioBroker.docker/blob/main/.github/workflows/build-debian-image-dev.yml
This is where I build the dev tag. It's perfect for testing. 
 Maybe you can show me your action, so I can compare. If it is private, you can give it to me in private or simply try fix it an make a pr.

**Comment by viceice** [comment]
> [EDIT] Sorry, maybe I got you wrong. You mean it might be a problem of build and push Action, right? 

yes, we use `docker buildx ...` directly, which is working fine for the linked repo

**Comment by EugenMayer** [comment]
I would smell that it is rather related to https://github.com/buanet/ioBroker.docker/blob/main/.github/workflows/build-debian12-latest.yml#L152 - removing untagged manifests. 

Maybe, right after the build, the ref count is yet not update as fast as expected, counting the just pushed manifests as untagged and thus removing them alltogether.

> Investigation result: Looks like the manifest generated for multiarch images by "build and push" action (with buildx) is not supported by Github container repo (ghcr.io). 

Is there any source to that? I had / have no such issues in https://github.com/EugenMayer/docker-image-unison

**Comment by buanet** [comment]
> I would smell that it is rather related to https://github.com/buanet/ioBroker.docker/blob/main/.github/workflows/build-debian12-latest.yml#L152 - removing untagged manifests.
> 
> Maybe, right after the build, the ref count is yet not update as fast as expected, counting the just pushed manifests as untagged and thus removing them alltogether.

Good point. I'll give it a try.

**Comment by buanet** [comment]
@EugenMayer Thanks for your hint! My test looks good. Deleting the untagged images was never a problem as I pushed a separate manifest before changing build process to multiarch build with build and push action...  I'll fix that with next release.

**Comment by buanet** [comment]
With [latest release](https://github.com/buanet/ioBroker.docker/releases/tag/v9.1.0) pulling from ghcr.io is now working.
