### ISSUE TITLE
Container fails to start without admin instance

### ISSUE THREAD

**Issue by chah90** [buanet/ioBroker.docker#332]
Hi,

I have an ioBroker instance on an Raspberry Pi Zero 2 using this great Docker image. To save RAM, I had disabled the admin instance via console when it is not needed. This worked well until the end of last year, before changes in the startup script for the hostname check result in a terminating error on startup:

```
There was a problem detecting the admin instance of your iobroker.
Make sure the ioBroker installation you use has an admin instance or try again with a fresh installation and restore your configuration.
For more details see https://docs.buanet.de/iobroker-docker-image/docs/#restore
```

I worked around the problem by not disabling the admin instance. But I get warnings about litte memory regularly, I really would like so save the ~50MB. Therefore my question: Is it possible to prevent the terminating error in the startup sequence without the need of an admin instance?

**Comment by Apollon77** [comment]
Or try to use compact mode and run admin in ame group as the controller ... then you save 25-30MB already

**Comment by chah90** [comment]
Thanks for the hint, I will try that 😊

**Comment by winnyschuster** [comment]
Maybe an ENV like NOADMIN=true can skip the test, for average users this test makes sense i think

**Comment by buanet** [comment]
It's included in new [beta release](https://github.com/buanet/ioBroker.docker/releases/tag/v8.1.0-beta.1). Please test.

Regards,
André

**Comment by chah90** [comment]
Works great, thanks for the quick solution😊
