### ISSUE TITLE
[Problem]: No error messages if restore fails

### ISSUE THREAD

**Issue by Marc-Berg** [buanet/ioBroker.docker#333]
### Description

When I initiate a restore via the maintenance script, there are no error messages if the backup file is missing or does not have the necessary access rights.

Please output appropriate messages with a reference to the "restore.log" file.

```
root@iobroker:/opt/iobroker# m restore
You are now going to perform a restore of your iobroker.
Do you want to continue [yes/no]? yes
Stopping ioBroker.....
Done.
Restoring ioBroker... root@iobroker:/opt/iobroker# 
```

### Image version

v8.0.0

### Docker logs

```shell
Existing installation of ioBroker detected in "/opt/iobroker".
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
Checking Database connection... Done.
 
Terminated
There was a problem detecting the admin instance of your iobroker.
Make sure the ioBroker installation you use has an admin instance or try again with a fresh installation and restore your configuration.
For more details see https://docs.buanet.de/iobroker-docker-image/docs/#restore
 
This Script will exit now.
 
--------------------------------------------------------------------------------
-------------------------     2023-04-10 07:38:03      -------------------------
--------------------------------------------------------------------------------
-----                                                                      -----
----- ██╗  ██████╗  ██████╗  ██████╗   ██████╗  ██╗  ██╗ ███████╗ ██████╗  -----
----- ██║ ██╔═══██╗ ██╔══██╗ ██╔══██╗ ██╔═══██╗ ██║ ██╔╝ ██╔════╝ ██╔══██╗ -----
----- ██║ ██║   ██║ ██████╔╝ ██████╔╝ ██║   ██║ █████╔╝  █████╗   ██████╔╝ -----
----- ██║ ██║   ██║ ██╔══██╗ ██╔══██╗ ██║   ██║ ██╔═██╗  ██╔══╝   ██╔══██╗ -----
----- ██║ ╚██████╔╝ ██████╔╝ ██║  ██║ ╚██████╔╝ ██║  ██╗ ███████╗ ██║  ██║ -----
----- ╚═╝  ╚═════╝  ╚═════╝  ╚═╝  ╚═╝  ╚═════╝  ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝ -----
-----                                                                      -----
-----              Welcome to your ioBroker Docker container!              -----
-----                    Startupscript is now running!                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                          System Information                          -----
-----                    arch:                x86_64                       -----
-----                    hostname:            iobroker                     -----
-----                                                                      -----
-----                          Version Information                         -----
-----                    image:               v8.0.0                       -----
-----                    build:               2023-04-07T23:45:19+00:00    -----
-----                    node:                v18.15.0                     -----
-----                    npm:                 9.5.0                        -----
-----                                                                      -----
-----                        Environment Variables                         -----
-----                    IOB_BACKITUP_EXTDB:  true                         -----
-----                    SETGID:              1000                         -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                   Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------
 
This is not the first run of this container. Skipping first run preparation.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in "/opt/iobroker".
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
Checking Database connection... Done.
 
Hostname in ioBroker matches the hostname of this container.
No action required.
 
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
IOB_BACKITUP_EXTDB is "true". Unlocking features... Done.
 
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker... 
 
##### #### ### ## # iobroker.js-controller log output # ## ### #### #####
host.iobroker check instance "system.adapter.admin.0" for host "iobroker"
host.iobroker check instance "system.adapter.discovery.0" for host "iobroker"
host.iobroker check instance "system.adapter.backitup.0" for host "iobroker"
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
```

**Comment by buanet** [comment]
It's included in new [beta release](https://github.com/buanet/ioBroker.docker/releases/tag/v8.1.0-beta.1). Please test.

Regards,
André

**Comment by Marc-Berg** [comment]
I was able to complete the test successfully.

**Comment by buanet** [comment]
Weitere mögliche Optimierungen des Restores über das Maintenance Script aus dem Discord Channel:

**1. Restore unterbinden wenn Startscript noch läuft**

> Wenn man versucht, den Restore zu starten, während das Init-Script noch läuft (das kann ja ein paar Minuten dauern), bricht dieser Versuch mit schwer zu reproduzierenden Fehlern ab, oft wird auch einfach die Konsole geschlossen, vorher ist eine Zehntelsekunde die Meldung "Timeout reached, Killing remaining processes" zu sehen. Vielleicht könnte das Restore Skript dieses im Vorab noch prüfen und den Restore Versuch mit einer entsprechenden Meldung abbrechen?

**2. Restore eines Backups von anderem Hostnamen - Admin startet nicht** 
Related to #188 ???

> Ein häufiger Fehler besteht ja lt. Forum darin, dass nach einem Restore auf einen vom Backup Hostnamen abweichenden Host Iobroker (Admin) nicht startet, ohne zielführende Hinweise in den Logs. Kannst Du das im restore Skript feststellen und eine Hinweis-Meldung ausgeben?

**3. Timeout für Restart nach Abschluss des Restores erhöhen**

> Die Abschlussmeldung nach erfolgreichem Restore ist nach meinem Geschmack zu kurz sichtbar, bevor der Container neu startet. Da stehen ja wichtige Hinweise drin, die man dadurch ggf. nicht mitbekommt.

**Comment by buanet** [comment]
@Marc-Berg Ich habe mir die Punkte vom Discord mal angesehen. 1 und 3 sind wip.
Bei Punkt 2 sehe ich eigentlich keinen Grund im Container tätig zu werden. Das sollte eigentlich nicht vorkommen. Wir hatten das Problem schon [früher mal](https://github.com/ioBroker/ioBroker.js-controller/issues/1450). Statt jetzt groß eine Prüfung oder Korrektur im Container zu machen, wäre es besser wenn das erst gar nicht vorkommt. :) 
Lässt sich das Verhalten denn konkret reproduzieren? Falls ja, dann sollten wir nochmal einen Issue im js-controller forcieren um der Sache auf den Grund zu gehen. 

MfG,
André 

PS: Ich lasse morgen ein paar Tests laufen, dann mache ich ein neues beta-image mit den letzten Änderungen.

**Comment by Marc-Berg** [comment]
zu 2.: Das Problem lässt sich zuverlässig reproduzieren, allerdings hat das "winnyschuster" im verlinkten Issue ja bereits getan. Mehr kann ich im Moment nicht beitragen, das Verhalten ist exakt so, wie dort beschrieben.

**Comment by buanet** [comment]
Ja, das Ding ist halt nur, dass der Issue bereits geschlossen ist und es ja eigentlich seit js-controller v4 gelöst sein sollte. Wird sich also so keiner mehr anschauen...

**Comment by Marc-Berg** [comment]
Okay, ich habe das jetzt nochmal mit einem blanken System durchgespielt und die jeweiligen Logs weggeschrieben. Nach dem Restore mit einem anderen Hostname startet keine der drei Instanzen (admin, backitup, discovery) mehr.
Eröffnest du jetzt ein neues Issue, wie in #1450 angekündigt? Dann würde ich meine Logs und mein Vorgehen darunter hängen.

**Comment by buanet** [comment]
New issue at js-controller is https://github.com/ioBroker/ioBroker.js-controller/issues/2241

**Comment by buanet** [comment]
I think everything here is on its way. The suggested feature(s) are available for testing in v8.1.0-beta.2 for testing. 
The restore problem will be monitored with #188.
So I'll close this now.

Regards,
André
