### ISSUE TITLE
Iobroker startet plötzlich nicht mehr: Checking Database connection... Failed.

### ISSUE THREAD

**Issue by m50434** [buanet/ioBroker.docker#334]
Hi,
ich habe vor ein paar Tagen auf die buanet:latest - Version geupdatet. Lief eigentlich auch problemlos. Habe nichts weiter an iobroker gemacht.

Heute war auf einmal nicht mehr die Admin-Console erreichbar. Die VIS z.B. lief interessanter Weise noch... aber Skripte wurden auch nicht mehr ausgeführt.

Ich habe daraufhin den Container erst neu gestartet, dann nochmal neu redeployed.
Jedoch erschein in "Step 3" immer folgender Fehler:

#############################################################
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
Re)setting permissions (This might take a while! Please be patient!)... Done.
 
Fixing "sudo-bug" by replacing sudo with gosu... Done.
 
Checking Database connection... Failed.
Please check your configuration and try again.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs).
 
This Script will exit now.

###########################################################

Leider sagt mir die Fehlermeldung nichts... und Google bringt mich auch nicht weiter.
Was kann ich tun?

**Comment by buanet** [comment]
Dieses Issue wird geschlossen.

Gründe:
* Problem Report nicht ausgefüllt
* "latest" ist keine Version
*  Log unvollständig

Bitte Problem Report korrekt ausfüllen und neuen Issue erstellen. Danke.

MfG,
André

PS: `Checking Database connection... Failed.` lässt darauf schließen, dass deine Datenbank nicht erreichbar ist. Leider gibt dein Issue keine Informationen zu deinem Setup her. So wird dir hier niemand helfen können.
Außerdem gehe ich nicht davon aus, dass es sich um ein generelles Problem mit dem Docker Image handelt. Bitte überdenke ob du wirklich einen neuen Issue erstellen willst oder ob deine Frage vielleicht unter [Discussions](https://github.com/buanet/ioBroker.docker/discussions) oder gar im [ioBroker Forum](https://forum.iobroker.net) besser aufgehoben ist. 

Vielen Dank für dein Verständnis.

**Comment by m50434** [comment]
Sorry, ja, dafür habe ich Verständnis.
IoBroker lief 3 Jahre problemlos und von jetzt auf gleich ging nichts mehr.
Es war ein "Panik-Issue". Sorry !!!
Habe nun mithilfe eines Backups und Backitup das System (nach 4 Stunden) komplett wieder herstellen können und es läuft.
Hoffentlich bleibts dabei. Sorry nochmal!
