### ISSUE TITLE
[Feature Request]: run ZWAVE is "true". Running setup script... only if needed

### ISSUE THREAD

**Issue by DutchmanNL** [buanet/ioBroker.docker#377]
### Description

When z-wave is used and variable set, this proces runs on every start. As a side effect it can take 1-5 minutes (depending on system ressource) to start the container.

As comparison, starting the container without this flag only takes 30 seconds. 

I assume its not needed to run this heavy startup procedure every time and it would be nice to avoid when not needed.

Current situation:
Z-wave startup scripts run on every container start causing delay in start

Wanted situation:
Only run the Z-ware scripts when needed to speed up restart proces

**Comment by buanet** [comment]
To be honest, I never used AVAHI or ZWAVE. :) 
If you had questioned me yesterday I would have sworn that I had build it to only run once at the very first start of a new container (like I did with some other things). I'll fix this with the next version. Thanks for the hint.

Regards,
André

**Comment by DutchmanNL** [comment]
> To be honest, I never used AVAHI or ZWAVE. :) If you had questioned me yesterday I would have sworn that I had build it to only run once at the very first start of a new container (like I did with some other things). I'll fix this with the next version. Thanks for the hint.
> 
> Regards, André

great thank you absolutely appreciate that you will take effort on it and move it to one time only !

**Comment by buanet** [comment]
Hey, I've looked into this topic. Since iobroker.zwave is deprecated and iobroker.zwave2 no longer relies on open-zwave (which is also unmaintained), I will remove the Z-Wave setup script and the ZWAVE environment variable in the upcoming v9 release. It appears that iobroker.zwave2 doesn't have any specific requirements, so we won't need any special settings when using the Docker container.

Regards,
André

**Comment by DutchmanNL** [comment]
Thats good to know so with zwave2 we don't need the env set to true, will test it good news !
