### ISSUE TITLE
[Problem]: avahi is broken in v9

### ISSUE THREAD

**Issue by TA2k** [buanet/ioBroker.docker#387]
### Description / Beschreibung

It looks like the avahi-daemon is not started correctly in v9

### Image version

v9

### Docker logs / Docker Protokoll

```shell
the selected advertiser, "avahi", isn't available on this platform. Reverting to "bonjour-hap"
```

**Comment by buanet** [comment]
Duplicate #384 
Hotfix will be available soon with v9.0.1
