### ISSUE TITLE
[Feature Request]: Improve "registering" the maintenance.sh script

### ISSUE THREAD

**Issue by agross** [buanet/ioBroker.docker#390]
### Description / Beschreibung

Instead of registering the maintenance script (`/opt/scripts/maintenance.sh`) as a Bash alias, symlink the script to `/bin` (in all variants like `m`, `maint`, `maintenance`).

Why?

- `docker exec <iob-container> maint` yields `"maint": executable file not found in $PATH`
- You need an interactive shell with a terminal attached to be able to execute the script, which makes the process more complicated than it needs to be: `docker exec -t <iob-container> bash -ic maint`

By symlinking the executable to e.g. `/bin/maint` in the Dockerfile running the maintenance script becomes trivial:

```sh
$ docker exec -u 1000:1000 <iob-container> maint
This script helps you manage your ioBroker container!
...
```

**Comment by buanet** [comment]
Sounds good. Have you tried the new option to call the maintenance script with the help of iobroker command?
`iob maint` or `iobroker mint`
Is this working with docker exec?

Regards,
André

**Comment by agross** [comment]
> Is this working with docker exec?

It is, and it either does not check whether the command is executed with uid `iobroker` or it automatically changes to that user.

```sh
$ docker exec iobroker-app-1 iob maintenance
This script helps you manage your ioBroker container!
...
```

**Comment by buanet** [comment]
This enhancement is included in [v9.1.0-beta.1](https://github.com/buanet/ioBroker.docker/releases/tag/v9.1.0-beta.1).
Feel free to test. :) 

Regards,
André

**Comment by agross** [comment]
Thanks, working as intended.

Not sure why the symlink is not set up once in the Dockerfile, though. Does it really need to be re-setup on every start of the container?

On top of that, if the symlink already exists from a previous run, setting up the symlink again will fail. Since [`iobroker_startup.sh` sets the `errexit` option](https://github.com/buanet/ioBroker.docker/blob/ac40e5a07a5d893198fa34312effefe3292540fb/debian12/scripts/iobroker_startup.sh#L4C1-L4C18) I guess starting the container a second time might fail. Even if it doesn't fail because of [Bash's option inheritance quirks](https://saveriomiroddi.github.io/Additional-shell-options-for-non-trivial-bash-shell-scripts/#inherit_errexit), the container will log the error message below.

```sh
agross@pi ~
$ ln -s ~/.bashrc ~/foo

agross@pi ~
$ ln -s ~/.bashrc ~/foo
ln: failed to create symbolic link '/home/agross/foo': File exists

agross@pi ~
$ echo $?
1
```

**Comment by agross** [comment]
I just noticed that symlinking is guarded by an `if`. Still, I don’t see why the container should set up things that can be handled during image creation.

**Comment by buanet** [comment]
> I just noticed that symlinking is guarded by an if. Still, I don’t see why the container should set up things that can be handled during image creation.

True. The if makes sure this runs only once...
The registering of the script is done to the startup procedure because it was the easiest way as this was implemented into the image. 😄 Originally the script was undocumented and just to support my lazy side...
I'll put this on my list. It's a good idea to put this into the dockerfile. 
Thank you.

Regards,
André

**Comment by buanet** [comment]
Done in [v9.1.0-beta.2](https://github.com/buanet/ioBroker.docker/releases/tag/v9.1.0-beta.2).
Thank you!
