### ISSUE TITLE
[Feature Request]: Improve SETUID/SETGID handling during startup

### ISSUE THREAD

**Issue by agross** [buanet/ioBroker.docker#397]
### Description / Beschreibung

https://github.com/buanet/ioBroker.docker/blob/ac40e5a07a5d893198fa34312effefe3292540fb/debian12/scripts/iobroker_startup.sh#L167

The `cat`/`grep`/`cut` pipeline can be replaced by:

* `id -u iobroker` to get the user ID
* `id -g iobroker` to get the group ID

of the `iobroker` user.

**Comment by buanet** [comment]
👍

**Comment by buanet** [comment]
Done in [v9.1.0-beta.2](https://github.com/buanet/ioBroker.docker/releases/tag/v9.1.0-beta.2).
Thank you!
