### ISSUE TITLE
[Feature Request]: Add more specific error message on database timeout

### ISSUE THREAD

**Issue by dadeppa** [buanet/ioBroker.docker#411]
### Description / Beschreibung

In short: Please add a specific debug message if database connection fails due timeout. 

In long:
After installing a new adapter I needed to connect an USB device, so I changed the docker config and restarted the container. Afterwards the system did not work any longer, error message was:
`Checking Database connection... Failed.
Please check your configuration and try again.`

Set ENV `DEBUG `to true to get more details, but forgot to safe the outputs. 
Switched some versions of the image (started from my stable running 8.1.0, went to latest / 9.0.1 and back).

Then set up ENV variables for `IOB_STATESDB_TYPE` / `IOB_OBJECTSDB_TYPE `/ ff to json and corresponding values. Ran into failed DB check again. 
Found [this](https://forum.iobroker.net/post/777325) post in ioBroker forums, changed `connectTimeout`  in `objects `and `states ` in `iobroker/iobroker-data/iobroker.json` and then ioBroker ran again. 
Took me quite a while to figure this out. I am not sure if there is a hint somewhere in the docs - did not find it yet. So I am requesting an additional debug / error message after checking db type / connection and running in an error due timeout. 

Thank you for the really good work ( :) ).

**Comment by buanet** [comment]
Not sure how to do that as ioBroker gives no specific output with the actual command i use for database check.

https://github.com/buanet/ioBroker.docker/blob/0cbfd67f5a97cfee8615c9434e34b54721340c72/debian12/scripts/iobroker_startup.sh#L334C28-L334C28

Any ideas?

Regards,
André

**Comment by dadeppa** [comment]
Hi Andre, 

sorry for keep you waiting. Tbh I am really low level linux user, so I hunted the script through ChatGPT, he suggested this at a first glace:
```echo -n "Checking Database connection... "
set +e
if gosu iobroker iob uuid &> /dev/null; then
  echo "Done."
  echo " "
else
  errormsg=$(gosu iobroker iob uuid 2>&1 | sed 's/^/[DEBUG] /')
  exit_status=$?
  set -e
  
  if [[ $exit_status -eq 124 ]]; then
    # Handle timeout error
    echo "Failed due to a timeout. The database might be too large."
    if [[ "$debug" == "true" ]]; then
      echo "[DEBUG] Error message: "
      echo "$errormsg"
    fi
    echo "Consider increasing the timeout or optimizing your database."
    echo "For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs)."
    stop_on_error
  else
    # Handle other errors
    echo "Failed."
    if [[ "$debug" == "true" ]]; then
      echo "[DEBUG] Error message: "
      echo "$errormsg"
    fi
    echo "Please check your configuration and try again."
    echo "For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs)."
    stop_on_error
  fi
fi
```

with the hints:

- The exit_status variable is introduced to capture the exit status of the gosu iobroker iob uuid command.
- If the exit status is 124, which typically indicates a timeout error, it will print a specific message and stop the script.
- If the exit status is different, it will handle other errors as before.

I am not sure whether it is possible to access the exit status in the way chat GPT suggests.

Another Thing is, if we know the timeout, we may just run a stopwatch and _**assume**_ that it depended on a timeout if the database connection is exiting after the timeout value from /opt/iobroker/iobroker-data
