### ISSUE TITLE
[Feature Request]: Podman support (rootless by default) in installation script.

### ISSUE THREAD

**Issue by andrico21** [buanet/ioBroker.docker#414]
### Description / Beschreibung

Hi. Long story short - I'm using Podman instead of Docker because Podman provides much more convenient way to run rootless containers out-of-the-box. Yes, setuid/setgid which implemented inside image are good enough, but Podman itself can implement additional layer of isolation - mapping container 'root' user to non-root user on a host.

```bash
cntmaster@pdlab:~$ podman exec -it iobroker id
uid=0(root) gid=0(root) groups=0(root)

cntmaster@pdlab:~$ id
uid=1001(cntmaster) gid=1001(cntmaster) groups=1001(cntmaster)

cntmaster@pdlab:~$ ps aux
cntmast+   29284  0.0  0.0  82720  3072 ?        Ssl  11:26   0:00 /usr/bin/conmon --api-version 1 -c 0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce -u 0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce -r /usr/bin/crun -b /home/cntmaster/.local/share/containers/storage/overlay-containers/0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce/userdata -p /tmp/podman-run-1001/containers/overlay-containers/0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce/userdata/pidfile -n iobroker --exit-dir /tmp/podman-run-1001/libpod/tmp/exits --full-attach -s -l journald --log-level warning --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/tmp/podman-run-1001/containers/overlay-containers/0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce/userdata/oci-log --conmon-pidfile /tmp/podman-run-1001/containers/overlay-containers/0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/cntmaster/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /tmp/podman-run-1001/containers --exit-command-arg --log-level --exit-command-arg warning --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /tmp/podman-run-1001/libpod/tmp --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 0bf33d12c62e0fcfa6ad1783727179f162815d4ef4a0ed96e1fb480481354cce

cntmaster@pdlab:~$ podman top iobroker
USER        PID         PPID        %CPU        ELAPSED           TTY         TIME        COMMAND
root        1           0           0.000       34m50.947216295s  ?           0s          bash /opt/scripts/iobroker_startup.sh
iobroker    542         1           0.350       33m20.947286327s  ?           7s          iobroker.js-controller
iobroker    564         542         0.200       33m19.947323713s  ?           4s          io.admin.0
iobroker    591         542         0.050       33m15.947365441s  ?           1s          io.discovery.0
iobroker    606         542         0.050       33m11.947400837s  ?           1s          io.backitup.0

cntmaster@pdlab:~$ podman top iobroker huser user
HUSER       USER
1001        root
166535      iobroker
166535      iobroker
166535      iobroker
166535      iobroker
```

I've got it running finally, but installer logic covers only Docker-specific checks like evaluating '/proc/self/cgroup' for 'docker'/'buildkit', .dockerenv presence etc.

The only mod required is to check for '**/run/.containerenv**' also - it's created by Podman as a flag.

just as an idea for container detection - it's also maybe reasonable to check '/' mount, in container it will be overlayed:
```bash
cat /proc/$$/mounts | grep -w "/"
overlay / overlay rw,relatime,lowerdir=/home/cntmaster/.local/share/containers/storage/overlay/l/DO4PTYLLQWT2Z5PS4QTPKVBHYF:/home/cntmaster/.local/share/containers/storage/overlay/l/5RREU2VA7GTZCH55VYGK2SZ73R:/home/cntmaster/.local/share/containers/storage/overlay/l/LMGTMMP7MCO2ICRIMDNUIP7WY5:/home/cntmaster/.local/share/containers/storage/overlay/l/TMTU73LUI2X4QYJK3EU5MDE6HE:/home/cntmaster/.local/share/containers/storage/overlay/l/RHDU6PQ7SPO4NHDJKRKZ6XWWJ5,upperdir=/home/cntmaster/.local/share/containers/storage/overlay/b76f17fe8c5f531df2d28f1d0d6b195d49b28438c4b545a19ca0e9b4abe0b23d/diff,workdir=/home/cntmaster/.local/share/containers/storage/overlay/b76f17fe8c5f531df2d28f1d0d6b195d49b28438c4b545a19ca0e9b4abe0b23d/work,userxattr 0 0
```

The only capabilities I had to add to already recommended NET_ADMIN are **CAP_NET_RAW** and **CAP_NET_BIND_SERVICE**.
```bash
podman run -d --name iobroker -h iobroker -p 8081:8081 -v iob-data:/opt/iobroker/ -e LANG=en_US.UTF-8 -e LANGUAGE="en_US:en" -e TZ="Asia/Dubai" --cap-add=CAP_NET_RAW --cap-add=NET_ADMIN --cap-add=CAP_NET_BIND_SERVICE iobroker:latest-v9
```

**Comment by buanet** [comment]
Hi,
what is the exact feature you are requesting?

Docker detection used by iobroker components should work like described [here](https://docs.buanet.de/iobroker-docker-image/docs/#notes-for-developers). We did this because detecting a container environment is difficult if you want to cover all cases. This should also work in Podman (and any other environment). 

That is all I can do from the Docker Image. All implementations of this Docker check have to be made in the adapters which need it or in iobroker (js-controller) itself. 

Regards,
André

**Comment by andrico21** [comment]
Hi, the only feature I suggest to add is to check run/.containerenv presence as one of OR conditions.
With cgroups v2 and podman existing check will not consider installation as containerized, isn't?

**Comment by EugenMayer** [comment]
I would also be interested in running this container as non-root on k8s. But i guess support for 
- "installing packages" via ENV and sorts of other things
- updating linux packages on start

force a root-based bootstrap, even though permissions are dropped to 1000/1000 later on.

The docker image would need to drop quiet some functionality, maybe even access on cricial parts like devices (usb) to become rootless IMHO.

So even though i would love to see it, i do not think it is practical in the case of ioBroker.

**Comment by buanet** [comment]
> check run/.containerenv presence as one of OR conditions.

As written above, all implementations of this Docker check have to be made in the adapters which need it or in iobroker (js-controller) itself. So this place might be the wrong place for this request. 
As long as you use the official image, iobroker should detect containerisation. Why? See the link from my last answer. 

> So even though i would love to see it, i do not think it is practical in the case of ioBroker.

Same here. I tried several times. ioBroker is sadly not specially made for Docker yet. I cutted root down to only the startup script runs as it. Maybe we could do the root-based bootstrap and then drop the root permissions, but this is not on top of my to-do list. :)  But it is there, i can prove it 😄 

![image](https://github.com/buanet/ioBroker.docker/assets/16137672/b421d6ea-3d68-4515-b1ac-e22581b64dd0)

Regards,
André

**Comment by andrico21** [comment]
> Docker detection used by iobroker components should work like described [here](https://docs.buanet.de/iobroker-docker-image/docs/#notes-for-developers). We did this because detecting a container environment is difficult if you want to cover all cases. This should also work in Podman (and any other environment).
Oh, finally realized - what you do mean here. So we're not relying on install.sh logic to detect if it's container-environment, but instead of that we're just have flag-file pre-created inside of image, right?

**Comment by buanet** [comment]
That's correct.
