### ISSUE TITLE
[Feature Request]: Add set -e to healthcheck.sh

### ISSUE THREAD

**Issue by EugenMayer** [buanet/ioBroker.docker#418]
### Description / Beschreibung

https://github.com/buanet/ioBroker.docker/blob/main/debian12/scripts/healthcheck.sh does not have `set -e` set

### Image version

9.0.1

### Docker logs / Docker Protokoll

For example if access failes to /opt/.docker_config/.healthcheck the result can be exit 0, even if it should not be

**Comment by buanet** [comment]
As there are no reported problems, this might be an possible enhancement.
Access will be checked/ corrected at every container start.  The described case should not happen at all.
Also affected by #420?

Nevertheless I think it's worth doing that. 

Regards,
André
