### ISSUE TITLE
[Feature Request]: migrate to PUID/PGID since it is the defacto standard

### ISSUE THREAD

**Issue by EugenMayer** [buanet/ioBroker.docker#419]
### Description / Beschreibung

Currently the way to set the PID/GID is using SETGID/SETUID.

The defacto standard in in this field is PUID/PGID and it is very widely adopted. [lsio](https://docs.linuxserver.io/general/understanding-puid-and-pgid/)/[hsio](https://hotio.dev/containers/autoscan/) and even helm chart libraries like [TrueCharts](https://truecharts.org/manual/SCALE/options/security) use it as an value to stear the security context derived user.

I think it would be valueable to at least support both (in addition) or deprecate the other 2 for some time.

Why it is valuable? Because people can use the boilerplate right away and are used to set this value to control which ownership the written files have (or had).

Thanks for considering tit

**Comment by buanet** [comment]
Sounds like a reasonable approach.

Regards,
André

**Comment by EugenMayer** [comment]
This will need further clarification. 

## Variant a) Implementing it to support "BOTH" (non braking)

1. most probably needs a utility function since the entire thing is spread all over the place.
2. needs to define if the variables should still be called setuid/setgid or we move to puid/pgid
3. 
This is def. more effort

## Variant b)

Move to PUID/PGID entirely

Simple and fast, but braking change
