### ISSUE TITLE
[Problem]: userscripts are not owned by the SETGID/SETUID user 

### ISSUE THREAD

**Issue by EugenMayer** [buanet/ioBroker.docker#420]
### Description / Beschreibung

if you set the SETGID/SETUID to something else (568:568 in my case), the user scripts are still owned by the default 1000:1000

Seems like it is not chowned in https://github.com/buanet/ioBroker.docker/blob/0cbfd67f5a97cfee8615c9434e34b54721340c72/debian11/scripts/iobroker_startup.sh#L229

### Image version

9.0.1

### Docker logs / Docker Protokoll

```shell
-
```

**Comment by buanet** [comment]
I see no error in that code. It is executed as long as env "PERMISSION_CHECK" is not set to false. 

This is the correct source: https://github.com/buanet/ioBroker.docker/blob/0cbfd67f5a97cfee8615c9434e34b54721340c72/debian12/scripts/iobroker_startup.sh#L245

Any ideas?

**Comment by buanet** [comment]
I was wrong here. :) It was late yesterday. You were talking about userscripts. For sure, this wasn't chowned... 
Thank you.

Regards, 
André
