### ISSUE TITLE
[Problem]: arm/v7 support 

### ISSUE THREAD

**Issue by buanet** [buanet/ioBroker.docker#429]
### Description / Beschreibung

Currently, there is no Arm/v7 version of the ioBroker Docker image available for the following tags: `latest`, `latest-v9` and ≥ `v9.1.0`. The last known functional tag is `v9.1.0-beta.3`.

Due to unresolved issues with the automatic image generation process for the Arm/v7 architecture, support is temporarily discontinued in v9.1.0 until there is sufficient time to investigate and potentially resolve these issues.

As I am uncertain whether anyone is utilizing the Arm/v7 version, this matter holds a lower priority for me. Please comment on this issue if you believe I should elevate its priority. Thank you.

Regards,
André

### Image version

v9.1.0

### Docker logs / Docker Protokoll

```shell
-
```

**Comment by gitvop** [comment]
Hello, I just ran into this problem while trying to pull the latest image on my RPI4, which serves as docker host for iobroker:

```
pi@pi4:~ $ docker pull buanet/iobroker
Using default tag: latest
latest: Pulling from buanet/iobroker
no matching manifest for linux/arm/v7 in the manifest list entries

```

I would very much welcome it if Arm/V7 is supported again :-)

**Comment by buanet** [comment]
Thank you for your feedback.

You mentioned that you have the ioBroker Docker image running on the Raspberry Pi 4.
The Raspberry Pi 4 supports 64-bit architecture. As far as I know, with the 64-bit version of Raspberry Pi OS, it should be possible to use the ARM64v8 Version of the ioBroker Docker image.

Is there a specific reason why you are using a 32-bit OS?

Sorry for this question, but I'm trying to find out if the ARMv7 Docker image is still truly necessary.
In case of the Raspberry Pi 4, I currently don't see this necessity due to its 64-bit support.

Regards,
André

**Comment by bpletzer** [comment]
Hi,
What about ARMv8?

docker pull buanet/iobroker:v9.1.0
v9.1.0: Pulling from buanet/iobroker
no matching manifest for linux/arm/v8 in the manifest list entries


and in any case, how do I buy you a coffee?

**Comment by buanet** [comment]
> What about ARMv8?

Should work as expected. See no Problem with my Raspberry Pi 4 and latest Raspberry OS 64-bit...

```
andre@raspi4-dev:~ $ docker pull buanet/iobroker:v9.1.0
v9.1.0: Pulling from buanet/iobroker
a5573528b1f0: Pull complete
574807d7c4ec: Pull complete
57f7206b43d3: Pull complete
2915fcd009f9: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:93d1c526c46fcc66846c5c24876a614800bdef07675d6730a07646dfa06992fe
Status: Downloaded newer image for buanet/iobroker:v9.1.0
docker.io/buanet/iobroker:v9.1.0
```

```
andre@raspi4-dev:~ $ docker image inspect buanet/iobroker:v9.1.0 | grep -e "Arch"
        "Architecture": "arm64",
```

**Comment by bpletzer** [comment]
most probably user problem on my side then

`iobroker@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

`iobroker@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

this is but after an upgrade from bullseye 32bit

I tried loading the specific platform, it says container starts but it doesn't really run
`iobroker@raspberrypi:~ $ docker pull buanet/iobroker:v9.1.0 --platform linux/arm64`

seems like I have to try with clean raspbian installed via image - just shied away from the effort of migrating

**Comment by Marty56** [comment]
I would be very grateful if you could continue to support the Arm7 architecture.
I am using an Orangepiplus2e which is working great using your docker.
It would be sad to see if I had to dump this otherwise flawless system.

**Comment by stefpb** [comment]
I have the same problem: I upgraded from v8.0.1 to v9.0.1

![image](https://github.com/buanet/ioBroker.docker/assets/1069441/1c21017b-ed73-43d3-997a-534d067ed124)

I also changed the raspbian of my raspberry 4 from 32bit to 64bit by adding `arm_64bit=1` to `/boot/config.txt` (found at https://www.bastianoso.de/tipps-tricks/raspberry-pi/raspberry-pi-os-auf-64-bit-umstellen.html)

What can i do?

**Comment by buanet** [comment]
@stefpb I think it's like @bpletzer said. There might be a problem when upgrading from 32-bit. I have a Raspberry Pi 4 with Raspberry Pi OS 64-bit and no problems with pulling the arm/v8 image... 

BUT: 🎉🎉🎉
I gave arm/v7 another try after I fixed ther nodejs setup as well as developers fixed it in the iobroker installer. Now arm/v7 build is working again. So @Marty56 @gitvop can you verify the image ist woking again (tags: v9.1.1, latest or latest-v9)?

I also updated the [v9.1.1 release notes](https://github.com/buanet/ioBroker.docker/releases/tag/v9.1.1). 

This should no longer be an issue. 

Regards,
André

**Comment by gitvop** [comment]
Thank you, already pulled latest-v9, container is running on 32bit OS on RPI4!
<img width="678" alt="image" src="https://github.com/buanet/ioBroker.docker/assets/110935634/22657325-057f-4946-8248-7f61050c10f8">

Reason why i'm still on 32bit is the same reason why i'm coming from a v5-image - no updates for a looong time ;-)

_(I was fine with it running smoothly and supporting all I needed, I only gave up the "never touch a running system" excuse because I want to try the Roborock adapter (required newer node, so the new S8 can become as smart as its S5 predecessor which was controlled by the xiaomi adapter)_

**Comment by Marty56** [comment]
Thanks for the fix. Just updated the iobroker docker image and it is working nicely.
