### ISSUE TITLE
[Problem]: Small typo in docs

### ISSUE THREAD

**Issue by RP70DP** [buanet/ioBroker.docker#437]
### Description / Beschreibung

See:
https://github.com/buanet/ioBroker.docker/blob/main/docs/README_docker_hub_iobroker.md

"IOB_STATESDB_PASS (optional, default: 9000) Set authentication for Redis db connection"

"default: 9000" is probably a copy & past mistake.

### Image version

v9.1.1

### Docker logs / Docker Protokoll

```shell
k.a.
```

**Comment by buanet** [comment]
Fixed. Thank you.
