### ISSUE TITLE
[Problem]: Use bundled npm version instead of latest / don't upgrade npm manually

### ISSUE THREAD

**Issue by klein0r** [buanet/ioBroker.docker#465]
### Description / Beschreibung

Remove this line

https://github.com/buanet/ioBroker.docker/blob/5247639a66ad0b648153c4da632795a99f45093c/debian12/Dockerfile#L49

### Image version

9.1.2

### Docker logs / Docker Protokoll

```shell
-
```

**Comment by buanet** [comment]
This is just a temporary fix...
