### ISSUE TITLE
[Problem]: Login on IObroker not possible 

### ISSUE THREAD

**Issue by Seven1969** [buanet/ioBroker.docker#469]
### Description / Beschreibung

Hi,
Updated to the latest version this morning. Now I am not able to login. The Iobroker Login Screen looks like in the screenshot.
Not able state user ot password. URL is  https://192.168.xxx.xxx:8081/?login&href=#tab-intro
Cleaned up the browsers chache, doesnt't wortk on Edge and Chorme even not on Mobile
 
![image](https://github.com/buanet/ioBroker.docker/assets/147832912/391d00cd-0105-4c55-a8a1-952894f3d0ed)

### Image version

latest 

### Docker logs / Docker Protokoll

```shell
Not present
```

**Comment by Apollon77** [comment]
That seesm to be an Admin issue, no docker issue

**Comment by Seven1969** [comment]
> That seesm to be an Admin issue, no docker issue

Happend after update to latest docker version this morning. Admin was updated to latest Beta Version yersterday without any issue.

**Comment by Seven1969** [comment]
Apollon77, you were right, the Admin has been updated. Issue is solved
