### ISSUE TITLE
Message: Betriebssystem update verfügbar

### ISSUE THREAD

**Issue by michiproep** [buanet/ioBroker.docker#481]
### Description / Beschreibung

iobroker is showing this message all the time:

`
base-files/stable 12.4+deb12u6 amd64 [upgradable from: 12.4+deb12u4]
bash/stable 5.2.15-2+b7 amd64 [upgradable from: 5.2.15-2+b2]
bsdutils/stable,stable-security 1:2.38.1-5+deb12u1 amd64 [upgradable from: 1:2.38.1-5+b1]
curl/stable 7.88.1-10+deb12u6 amd64 [upgradable from: 7.88.1-10+deb12u5]
gir1.2-gdkpixbuf-2.0/stable 2.42.10+dfsg-1+deb12u1 amd64 [upgradable from: 2.42.10+dfsg-1+b1]
gosu/stable 1.14-1+b10 amd64 [upgradable from: 1.14-1+b6]
libarchive13/stable,stable-security 3.6.2-1+deb12u1 amd64 [upgradable from: 3.6.2-1]
libblkid-dev/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libblkid1/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libc-bin/stable,stable-security 2.36-9+deb12u7 amd64 [upgradable from: 2.36-9+deb12u4]
libc-dev-bin/stable,stable-security 2.36-9+deb12u7 amd64 [upgradable from: 2.36-9+deb12u4]
libc-l10n/stable,stable-security 2.36-9+deb12u7 all [upgradable from: 2.36-9+deb12u4]
libc6-dev/stable,stable-security 2.36-9+deb12u7 amd64 [upgradable from: 2.36-9+deb12u4]
libc6/stable,stable-security 2.36-9+deb12u7 amd64 [upgradable from: 2.36-9+deb12u4]
libcurl3-gnutls/stable 7.88.1-10+deb12u6 amd64 [upgradable from: 7.88.1-10+deb12u5]
libcurl4/stable 7.88.1-10+deb12u6 amd64 [upgradable from: 7.88.1-10+deb12u5]
libfreetype-dev/stable 2.12.1+dfsg-5+deb12u3 amd64 [upgradable from: 2.12.1+dfsg-5]
libfreetype6/stable 2.12.1+dfsg-5+deb12u3 amd64 [upgradable from: 2.12.1+dfsg-5]
libgdk-pixbuf-2.0-0/stable 2.42.10+dfsg-1+deb12u1 amd64 [upgradable from: 2.42.10+dfsg-1+b1]
libgdk-pixbuf-2.0-dev/stable 2.42.10+dfsg-1+deb12u1 amd64 [upgradable from: 2.42.10+dfsg-1+b1]
libgdk-pixbuf2.0-bin/stable 2.42.10+dfsg-1+deb12u1 amd64 [upgradable from: 2.42.10+dfsg-1+b1]
libgdk-pixbuf2.0-common/stable 2.42.10+dfsg-1+deb12u1 all [upgradable from: 2.42.10+dfsg-1]
libglib2.0-0/stable 2.74.6-2+deb12u3 amd64 [upgradable from: 2.74.6-2]
libglib2.0-bin/stable 2.74.6-2+deb12u3 amd64 [upgradable from: 2.74.6-2]
libglib2.0-data/stable 2.74.6-2+deb12u3 all [upgradable from: 2.74.6-2]
libglib2.0-dev-bin/stable 2.74.6-2+deb12u3 amd64 [upgradable from: 2.74.6-2]
libglib2.0-dev/stable 2.74.6-2+deb12u3 amd64 [upgradable from: 2.74.6-2]
libgnutls30/stable 3.7.9-2+deb12u3 amd64 [upgradable from: 3.7.9-2+deb12u1]
libgssapi-krb5-2/stable-security 1.20.1-2+deb12u2 amd64 [upgradable from: 1.20.1-2+deb12u1]
libisl23/stable 0.25-1.1 amd64 [upgradable from: 0.25-1]
libk5crypto3/stable-security 1.20.1-2+deb12u2 amd64 [upgradable from: 1.20.1-2+deb12u1]
libkrb5-3/stable-security 1.20.1-2+deb12u2 amd64 [upgradable from: 1.20.1-2+deb12u1]
libkrb5support0/stable-security 1.20.1-2+deb12u2 amd64 [upgradable from: 1.20.1-2+deb12u1]
libmount-dev/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libmount1/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libpython3.11-dev/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
libpython3.11-minimal/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
libpython3.11-stdlib/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
libpython3.11/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
libseccomp2/stable 2.5.4-1+deb12u1 amd64 [upgradable from: 2.5.4-1+b3]
libsmartcols1/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libssl3/stable 3.0.13-1~deb12u1 amd64 [upgradable from: 3.0.11-1~deb12u2]
libsystemd0/stable 252.26-1~deb12u2 amd64 [upgradable from: 252.19-1~deb12u1]
libudev-dev/stable 252.26-1~deb12u2 amd64 [upgradable from: 252.19-1~deb12u1]
libudev1/stable 252.26-1~deb12u2 amd64 [upgradable from: 252.19-1~deb12u1]
libuuid1/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
libuv1/stable,stable-security 1.44.2-1+deb12u1 amd64 [upgradable from: 1.44.2-1]
linux-libc-dev/stable-security 6.1.99-1 amd64 [upgradable from: 6.1.69-1]
locales/stable,stable-security 2.36-9+deb12u7 all [upgradable from: 2.36-9+deb12u4]
mount/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
nodejs/nodistro 18.20.4-1nodesource1 amd64 [upgradable from: 18.19.0-1nodesource1]
openssl/stable 3.0.13-1~deb12u1 amd64 [upgradable from: 3.0.11-1~deb12u2]
python3.11-dev/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
python3.11-minimal/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
python3.11/stable 3.11.2-6+deb12u2 amd64 [upgradable from: 3.11.2-6]
tar/stable 1.34+dfsg-1.2+deb12u1 amd64 [upgradable from: 1.34+dfsg-1.2]
tzdata/stable 2024a-0+deb12u1 all [upgradable from: 2023c-5+deb12u1]
udev/stable 252.26-1~deb12u2 amd64 [upgradable from: 252.19-1~deb12u1]
usr-is-merged/stable 37~deb12u1 all [upgradable from: 35]
util-linux-extra/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
util-linux/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
uuid-dev/stable,stable-security 2.38.1-5+deb12u1 amd64 [upgradable from: 2.38.1-5+b1]
`

I already upgraded the host system. How can this be fixed?
Thanks in advance!

### Image version

9.1.2

### Docker logs / Docker Protokoll

```shell
none
```

**Comment by Apollon77** [comment]
You need to acknowledge the message in the dialog and not just close the window with "ok" :-)

We already work on optimizations for the display but please check of you really ack it

**Comment by michiproep** [comment]
I did. But it keeps showing up after "every click" (Tab change)

**Comment by Marc-Berg** [comment]
The images are constantly kept up to date without the version changing. Have you downloaded the latest image recently?

**Comment by michiproep** [comment]
I usually pull the latest image whenever I see a new version/release here

**Comment by Marc-Berg** [comment]
The image was last updated 12 hours ago.

![grafik](https://github.com/user-attachments/assets/4c95addf-aeac-463e-8e74-b75c47aeada3)

**Comment by buanet** [comment]
As Marc said. Make sure you downloaded the latest image and confirm the message in admin. There are still some optimizations pending, see [this issue](https://github.com/ioBroker/ioBroker.js-controller/issues/2842).
You can also try to set environment variable PACKAGESUPDATE to true. This will update all packages within the first start/ recreation of your container. This feature is undocumented at the moment cause it is in experimental state but will be part of upcoming v10. 

Regards,
André

**Comment by michiproep** [comment]
thanks for the info. worked.
we can close this

**Comment by Marc-Berg** [comment]
> You can also try to set environment variable PACKAGESUPDATE to true.

I tried this as it did not work, small correction: The environment variable is called PACKAGES_UPDATE. :-)

**Comment by buanet** [comment]
> The environment variable is called PACKAGES_UPDATE. :-)

You are absolutely right. :) I missed the underscore... Thanks!

Regards,
André
